Improved error handling and added file check

diff --git a/omniopt_share b/omniopt_share
--- a/omniopt_share
+++ b/omniopt_share
@@ -321,28 +321,32 @@
 				fi
 			fi
 
-			if [[ $DEBUG -eq 1 ]]; then
-				echo "curl -s ${curl_options[@]} $url"
-			fi
-
-			set +e
-
-			CURL_OUTPUT=$(curl -s "${curl_options[@]}" "$url")
-			exit_code=$?
-
-			set -e
-
-			if [[ $exit_code -ne 0 ]] || echo "$CURL_OUTPUT" | grep "Error sharing the job." >/dev/null 2>&1 ; then
-				red_text "$CURL_OUTPUT"
-				if [[ $exit_code -ne 0 ]]; then
-					echo "Curling $url failed. Curl exited with $exit_code instead of 0"
-					if [[ $exit_code == 7 ]]; then
-						echo "Exit code 7 means that the server was not reachable. Are you online? Is the server properly started?"
-					fi
-					exit $exit_code
-				fi
+			if [ ${#curl_options[@]} -eq 0 ]; then
+				red_text "Could not find any files in $RUN_DIR\n"
 			else
-				green_text "$CURL_OUTPUT"
+				if [[ $DEBUG -eq 1 ]]; then
+					echo "curl -s ${curl_options[@]} $url"
+				fi
+
+				set +e
+
+				CURL_OUTPUT=$(curl -s "${curl_options[@]}" "$url")
+				exit_code=$?
+
+				set -e
+
+				if [[ $exit_code -ne 0 ]] || echo "$CURL_OUTPUT" | grep "Error sharing the job." >/dev/null 2>&1 ; then
+					red_text "$CURL_OUTPUT"
+					if [[ $exit_code -ne 0 ]]; then
+						echo "Curling $url failed. Curl exited with $exit_code instead of 0"
+						if [[ $exit_code == 7 ]]; then
+							echo "Exit code 7 means that the server was not reachable. Are you online? Is the server properly started?"
+						fi
+						exit $exit_code
+					fi
+				else
+					green_text "$CURL_OUTPUT"
+				fi
 			fi
 
 			#if [[ -e $everything_but_singleruns ]] && [[ $keep_tmp_dir -eq 0 ]]; then
