introduced _fatal_error globally

diff --git a/.tests/find_undocumented_exit_codes b/.tests/find_undocumented_exit_codes
--- a/.tests/find_undocumented_exit_codes
+++ b/.tests/find_undocumented_exit_codes
@@ -4,9 +4,14 @@
 
 errors=0
 
-for found_exit_code in $(grep -e "exit.[0-9]" omniopt .omniopt.py | sed -e 's#.*exit.##' | sed -e 's#).*##' | sort | grep -v "^0$" | sort -nr | uniq); do
-	if ! cat .gui/exit_code_table.php | sed -e 's#^[[:space:]]*##' | grep "^$found_exit_code => " 2>/dev/null >/dev/null; then
-		echo -e "Failed: Undocumented exit-code $found_exit_code found"
+for code in $(
+		(
+			grep -hPo 'my_exit\s*\(\s*\K\d+' omniopt .omniopt.py
+			grep -hPo '_fatal_error\s*\(.*?,\s*\K\d+' omniopt .omniopt.py
+		) | sort -n | uniq | grep -v '^0$'
+	); do
+	if ! grep -q "^[[:space:]]*$code =>" .gui/exit_code_table.php; then
+		echo "Missing exit code: $code"
 		errors=1
 	fi
 done
