fix

diff --git a/ax/.tests/missing_descriptions_in_plots b/ax/.tests/missing_descriptions_in_plots
--- a/ax/.tests/missing_descriptions_in_plots
+++ b/ax/.tests/missing_descriptions_in_plots
@@ -3,6 +3,11 @@
 cnt=0
 
 for i in $(ls .omniopt_plot_*.py); do
+	if ! grep -q "# EXPECTED FILES" $i; then
+		echo "Missing '# EXPECTED FILES' in $i"
+		cnt=$(($cnt + 1))
+	fi
+
 	if ! grep -q "# DESCRIPTION" $i; then
 		echo "Missing '# DESCRIPTION' in $i"
 		cnt=$(($cnt + 1))
