new version

diff --git a/ax/.tests/plots b/ax/.tests/plots
--- a/ax/.tests/plots
+++ b/ax/.tests/plots
@@ -224,59 +224,67 @@ for _command in "${_commands[@]}"; do
 	END_TIME=$SECONDS
 	RUN_TIME=$(($END_TIME-$START_TIME))
 
-	if [[ "$projectname" == "no_result" ]] || [[ "$projectname" == "defective_files" ]] || [[ "$projectname" == "empty_resultsfile" ]] ; then
-		true # Do nothing here. Do not count jobs in these folders as fails
-	else
-		if [[ "$_exit_code" -ne 0 ]]; then
+	if [[ "$projectname" == "nonutf8" ]]; then
+		if [[ "$_exit_code" -ne 7 ]]; then
 			echo ""
-			red_text "$_command failed"
-			errors+=("$_command failed")
-		fi
-	fi
-
-	if [[ -e "$this_img" ]]; then
-		if [[ $(cat "$this_img" | grep svg | wc -l 2>/dev/null) -lt 2 ]]; then
-			echo ""
-			red_text "$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code"
-			errors+=("$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code")
-		else
-			MISSING_OUTPUTS=()
-
-			saved_IFS=$IFS
-			IFS=$'\n'
-			for needed_output in $(cat .omniopt_plot_${possible_plot_type}.py | grep "TEST_OUTPUT_MUST_CONTAIN" | sed -e 's#.*TEST_OUTPUT_MUST_CONTAIN:\s##g'); do
-				if ! grep "$needed_output" "$this_img" 2>/dev/null >/dev/null; then
-					MISSING_OUTPUTS+=("$needed_output")
-				fi
-			done
-
-			if [ ${#MISSING_OUTPUTS[@]} -eq 0 ]; then
-				green_reset_line "$PROGRESSBAR OK Plot-Tests $possible_plot_type/$this_img"
-				if [[ "$keep_tmp" -eq 0 ]]; then
-					rm -f "$this_img" || {
-						echo ""
-						red_text "Could not remove $this_img. ls -aslrt1:"
-						ls -aslrt1 "$this_img"
-						exit 5
-					}
-				fi
-			else
-				if [[ "$possible_plot_type" == "no_result" ]]; then
-					missing_outputs_str=$(join_by ", " $MISSING_OUTPUTS)
-					echo ""
-					red_text "$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code"
-					errors+=("$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code")
-				fi
-			fi
-			IFS=$saved_IFS
+			red_text "$_command failed. Required exit-code: 7"
+			errors+=("$_command failed. Required exit-code: 7")
 		fi
 	else
 		if [[ "$projectname" == "no_result" ]] || [[ "$projectname" == "defective_files" ]] || [[ "$projectname" == "empty_resultsfile" ]] ; then
-			green_reset_line "$PROGRESSBAR OK Plot-Tests $possible_plot_type/$this_img"
+			true # Do nothing here. Do not count jobs in these folders as fails
 		else
-			echo ""
-			red_text "$_command: $this_img does not exist"
-			errors+=("$_command: $this_img does not exist")
+			if [[ "$_exit_code" -ne 0 ]]; then
+				echo ""
+				red_text "$_command failed"
+				errors+=("$_command failed")
+			fi
+		fi
+
+		if [[ -e "$this_img" ]]; then
+			if [[ $(cat "$this_img" | grep svg | wc -l 2>/dev/null) -lt 2 ]]; then
+				echo ""
+				red_text "$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code"
+				errors+=("$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code")
+			else
+				MISSING_OUTPUTS=()
+
+				saved_IFS=$IFS
+				IFS=$'\n'
+				for needed_output in $(cat .omniopt_plot_${possible_plot_type}.py | grep "TEST_OUTPUT_MUST_CONTAIN" | sed -e 's#.*TEST_OUTPUT_MUST_CONTAIN:\s##g'); do
+					if ! grep "$needed_output" "$this_img" 2>/dev/null >/dev/null; then
+						MISSING_OUTPUTS+=("$needed_output")
+					fi
+				done
+
+				if [ ${#MISSING_OUTPUTS[@]} -eq 0 ]; then
+					green_reset_line "$PROGRESSBAR OK Plot-Tests $possible_plot_type/$this_img"
+					if [[ "$keep_tmp" -eq 0 ]]; then
+						rm -f "$this_img" || {
+							echo ""
+							red_text "Could not remove $this_img. ls -aslrt1:"
+							ls -aslrt1 "$this_img"
+							exit 5
+						}
+					fi
+				else
+					if [[ "$possible_plot_type" == "no_result" ]]; then
+						missing_outputs_str=$(join_by ", " $MISSING_OUTPUTS)
+						echo ""
+						red_text "$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code"
+						errors+=("$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code")
+					fi
+				fi
+				IFS=$saved_IFS
+			fi
+		else
+			if [[ "$projectname" == "no_result" ]] || [[ "$projectname" == "defective_files" ]] || [[ "$projectname" == "empty_resultsfile" ]] ; then
+				green_reset_line "$PROGRESSBAR OK Plot-Tests $possible_plot_type/$this_img"
+			else
+				echo ""
+				red_text "$_command: $this_img does not exist"
+				errors+=("$_command: $this_img does not exist")
+			fi
 		fi
 	fi
 	i=$(($i+1))
