fix

diff --git a/ax/.tests/start_simple_optimization_run b/ax/.tests/start_simple_optimization_run
--- a/ax/.tests/start_simple_optimization_run
+++ b/ax/.tests/start_simple_optimization_run
@@ -8,67 +8,68 @@ MAGENTA='\033[0;35m'
 NC='\033[0m'
 
 function set_debug {
-	trap 'echo -e "${CYAN}$(date +"%Y-%m-%d %H:%M:%S")${NC} ${MAGENTA}| Line: $LINENO | Exit: $? ${NC}${YELLOW}-> ${NC}${BLUE}[DEBUG]${NC} ${GREEN}$BASH_COMMAND${NC}"' DEBUG
+    trap 'echo -e "${CYAN}$(date +"%Y-%m-%d %H:%M:%S")${NC} ${MAGENTA}| Line: $LINENO | Exit: $? ${NC}${YELLOW}-> ${NC}${BLUE}[DEBUG]${NC} ${GREEN}$BASH_COMMAND${NC}"' DEBUG
 }
 
 function unset_debug {
-	trap - DEBUG
+    trap - DEBUG
 }
 
 export OO_MAIN_TESTS=1
 
 int_re='^[+-]?[0-9]+$'
+
 function echoerr() {
-	echo "$@" 1>&2
+    echo "$@" 1>&2
 }
 
 function yellow_text {
-	echoerr -e "\e\033[0;33m$1\e[0m"
+    echoerr -e "\e\033[0;33m$1\e[0m"
 }
 
 function red_text {
-	echoerr -e "\e[31m$1\e[0m"
+    echoerr -e "\e[31m$1\e[0m"
 }
 
 function green_text {
-	echoerr -e "\e\033[0;32m$1\e[0m"
+    echoerr -e "\e\033[0;32m$1\e[0m"
 }
 
 function calltracer () {
-	if [[ $EXPECTED_TO_FAIL -ne "1" ]]; then
-		yellow_text "Git status hash:"
-		git rev-parse HEAD
-		red_text 'Error occurred in file/line:'
-		caller
-	fi
+    if [[ $EXPECTED_TO_FAIL -ne "1" ]]; then
+        yellow_text "Git status hash:"
+        git rev-parse HEAD
+        red_text 'Error occurred in file/line:'
+        caller
+    fi
 }
 
 trap 'calltracer' ERR
 
 function help () {
-	echo "Possible options:"
-	echo "  --max_eval=(INT)                                   Number of max evals for this test"
-	echo "  --mem_gb=(INT)                                     Mem in GB (0 for all)"
-	echo "  --num_parallel_jobs (INT)                          Number of max parallel workers for this test"
-	echo "  --num_random_steps=(INT)                           Number of random steps"
-	echo "  --model=STR                                        Model name"
-	echo "  --gridsearch                                       Do gridsearch"
-	echo "  --gpus=(INT)                                       Nr of GPUs per worker"
-	echo "  --time=(INT)                                       Time each subjob should run"
-	echo "  --allow_failure                                    Adds a param to randomly fail"
-	echo "  --force_local_execution                            Execute locally even when slurm is installed"
-	echo "  --help                                             This help"
-	echo "  --debug                                            Enables debug mode"
-	exit $1
+    echo "Possible options:"
+    echo "  --max_eval=(INT)                                   Number of max evals for this test"
+    echo "  --mem_gb=(INT)                                     Mem in GB (0 for all)"
+    echo "  --num_parallel_jobs (INT)                          Number of max parallel workers for this test"
+    echo "  --num_random_steps=(INT)                           Number of random steps"
+    echo "  --model=STR                                        Model name"
+    echo "  --gridsearch                                       Do gridsearch"
+    echo "  --gpus=(INT)                                       Nr of GPUs per worker"
+    echo "  --time=(INT)                                       Time each subjob should run"
+    echo "  --allow_failure                                    Adds a param to randomly fail"
+    echo "  --force_local_execution                            Execute locally even when slurm is installed"
+    echo "  --help                                             This help"
+    echo "  --debug                                            Enables debug mode"
+    exit $1
 }
 
 NUM_GPUS=0
-if command -v nvidia-smi 2>/dev/null >/dev/null; then
-	NUM_GPUS=$(nvidia-smi --list-gpus | wc -l)
+if command -v nvidia-smi >/dev/null 2>&1; then
+    NUM_GPUS=$(nvidia-smi --list-gpus | wc -l)
 fi
 
 if [[ "$NUM_GPUS" -ne "0" ]]; then
-	NUM_GPUS=1
+    NUM_GPUS=1
 fi
 
 export gridsearch=0
@@ -82,383 +83,133 @@ time=60
 model=BOTORCH_MODULAR
 mem_gb=4
 
+function parse_argument() {
+    local arg="$1"
+    local var_name="$2"
+    local is_int="$3"
+
+    if [[ "$arg" == *=* ]]; then
+        value="${arg#*=}"
+    else
+        value="$2"
+        shift
+    fi
+
+    if [[ -n $value ]]; then
+		if [[ "$is_int" -eq 1 ]]; then
+			if ! [[ "$value" =~ $int_re ]]; then
+				red_text "error: --${var_name} not a INT: $arg" >&2
+				exit 100
+			fi
+		fi
+	fi
+
+    eval "$var_name=\"$value\""
+}
+
+function build_omniopt_command() {
+    local base_cmd=("./omniopt" "--live_share" "--send_anonymized_usage_stats" "--partition" "$PARTITION" "--experiment_name" "$TESTNAME" "--mem_gb=$mem_gb" "--time" "$time" "--worker_timeout=5" "--max_eval" "$max_eval" "--num_parallel_jobs" "$num_parallel_jobs" "--gpus" "$NUM_GPUS" "--run_program" "$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0)" "--parameter" "int_param range -100 10 int" "--parameter" "float_param range -100 10 float" "--parameter" "choice_param choice 1,2,4,8,16,hallo" "--parameter" "int_param_two range -100 10 int" "--follow" "--num_random_steps" "$num_random_steps" "--model" "$model" "--auto_exclude_defective_hosts" "--hide_ascii_plots")
+
+    if [[ "$gridsearch" -eq "1" ]]; then
+        base_cmd+=("--gridsearch")
+    fi
+
+    if [[ "$allow_failure" -eq "1" ]]; then
+        base_cmd+=("--parameter" "fail_or_not choice \"0,1\"")
+        local index=$(echo "${base_cmd[@]}" | grep -o -- '--run_program [^ ]*' | awk '{print NR}')
+        base_cmd=("${base_cmd[@]/%--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0)/$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0)}" )
+    fi
+
+    if [[ "$force_local_execution" -eq "1" ]]; then
+        base_cmd+=("--force_local_execution")
+    fi
+
+    echo "${base_cmd[@]}"
+}
+
 args=("$@")
 k=0
 while [ $k -lt ${#args[@]} ]; do
-	i="${args[k]}"
+    i="${args[k]}"
 
-	case $i in
-		--force_local_execution)
-			force_local_execution=1
-			;;
-		--allow_failure)
-			allow_failure=1
-			;;
-		--gridsearch)
-			gridsearch=1
-			shift
-			;;
-
-		--mem_gb=*)
-			mem_gb="${i#*=}"
-			if ! [[ $mem_gb =~ $int_re ]] ; then
-				red_text "error: --mem_gb not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--mem_gb)
-			shift
-			k=$((k+1))
-
-			mem_gb="${args[k]}"
-			if ! [[ $mem_gb =~ $int_re ]] ; then
-				red_text "error: --mem_gb not a INT: $i" >&2
-				exit 100
-			fi
-			;;
-
-		--time=*)
-			time="${i#*=}"
-			if ! [[ $time =~ $int_re ]] ; then
-				red_text "error: --time not a INT: $i" >&2
-				exit 100
-			fi
-			;;
-		--time)
-			shift
-			k=$((k+1))
-
-			time="${args[k]}"
-			if ! [[ $time =~ $int_re ]] ; then
-				red_text "error: --time not a INT: $i" >&2
-				exit 100
-			fi
-			;;
-		--max_eval=*)
-			max_eval="${i#*=}"
-			if ! [[ $max_eval =~ $int_re ]] ; then
-				red_text "error: --max_eval not a INT: $i" >&2
-				exit 100
-			fi
-			;;
-		--max_eval)
-			shift
-			k=$((k+1))
-
-			max_eval="${args[k]}"
-			if ! [[ $max_eval =~ $int_re ]] ; then
-				red_text "error: --max_eval not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-
-		--model=*)
-			model="${i#*=}"
-			;;
-		--model)
-			shift
-			k=$((k+1))
-
-			model="${args[k]}"
-			;;
-
-		--num_random_steps=*)
-			num_random_steps="${i#*=}"
-			if ! [[ $num_random_steps =~ $int_re ]] ; then
-				red_text "error: --num_random_steps not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--num_random_steps)
-			shift
-			k=$((k+1))
-
-			num_random_steps="${args[k]}"
-			if ! [[ $num_random_steps =~ $int_re ]] ; then
-				red_text "error: --num_random_steps not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--num_parallel_jobs=*)
-			num_parallel_jobs="${i#*=}"
-			if ! [[ $num_parallel_jobs =~ $int_re ]] ; then
-				red_text "error: --num_parallel_jobs not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--num_parallel_jobs)
-			shift
-			k=$((k+1))
-
-			num_parallel_jobs="${args[k]}"
-			if ! [[ $num_parallel_jobs =~ $int_re ]] ; then
-				red_text "error: --num_parallel_jobs not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--gpus=*)
-			NUM_GPUS="${i#*=}"
-			if ! [[ $NUM_GPUS =~ $int_re ]] ; then
-				red_text "error: --gpus not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--gpus)
-			shift
-			k=$((k+1))
-
-			NUM_GPUS="${args[k]}"
-			if ! [[ $NUM_GPUS =~ $int_re ]] ; then
-				red_text "error: --gpus not a INT: $i" >&2
-				exit 100
-			fi
-			;;
-
-		--help*)
-			help 0
-			;;
-		--debug)
-			debug=1
-			;;
-
-		*)
-			red_text "Unknown parameter $i"
-			exit 2
-			;;
-	esac
-	k=$((k+1))
+    case $i in
+        --force_local_execution)
+            force_local_execution=1
+            ;;
+        --allow_failure)
+            allow_failure=1
+            ;;
+        --gridsearch)
+            gridsearch=1
+            ;;
+        --mem_gb=*|--mem_gb)
+            parse_argument "$i" "mem_gb" 1
+            ;;
+        --time=*|--time)
+            parse_argument "$i" "time" 1
+            ;;
+        --max_eval=*|--max_eval)
+            parse_argument "$i" "max_eval" 1
+            ;;
+        --model=*|--model)
+            parse_argument "$i" "model" 0
+            ;;
+        --num_random_steps=*|--num_random_steps)
+            parse_argument "$i" "num_random_steps" 1
+            ;;
+        --num_parallel_jobs=*|--num_parallel_jobs)
+            parse_argument "$i" "num_parallel_jobs" 1
+            ;;
+        --gpus=*|--gpus)
+            parse_argument "$i" "NUM_GPUS" 1
+            ;;
+        --gpus)
+            k=$((k+1))
+            NUM_GPUS="${args[k]}"
+            ;;
+        --help*)
+            help 0
+            ;;
+        --debug)
+            debug=1
+            ;;
+        *)
+            red_text "Unknown parameter $i"
+            exit 2
+            ;;
+    esac
+    k=$((k+1))
 done
 
 if [[ "$num_parallel_jobs" -lt "1" ]]; then
-	red_text "num_parallel_jobs must be 1 or more, is $num_parallel_jobs"
-	exit 1
+    red_text "num_parallel_jobs must be 1 or more, is $num_parallel_jobs"
+    exit 1
 fi
 
 if [[ "$max_eval" -lt "1" ]]; then
-	red_text "Max_eval must be 1 or more, is $max_eval"
-	exit 1
+    red_text "Max_eval must be 1 or more, is $max_eval"
+    exit 1
 fi
 
 if [[ "$debug" -eq "1" ]]; then
-	set_debug
+    set_debug
 fi
 
 PARTITION="alpha"
 TESTNAME=__main__tests__
 
 if [[ "$force_local_execution" -eq "1" ]]; then
-	if [[ "$gridsearch" -eq "1" ]]; then
-		TESTNAME="${TESTNAME}_gridsearch"
-		if [[ "$allow_failure" -eq "0" ]]; then
-			./omniopt \
-				--force_local_execution \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_local" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--hide_ascii_plots
-			exit_code=$?
-		else
-			./omniopt \
-				--force_local_execution \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_local_allow_failure" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--gridsearch \
-				--hide_ascii_plots
-			exit_code=$?
-		fi
-	else
-		if [[ "$allow_failure" -eq "0" ]]; then
-			./omniopt \
-				--force_local_execution \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_local" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--hide_ascii_plots
-			exit_code=$?
-		else
-			./omniopt \
-				--force_local_execution \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_local_allow_failure" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--parameter fail_or_not choice "0,1" \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--hide_ascii_plots
-			exit_code=$?
-		fi
-	fi
+    TESTNAME="${TESTNAME}_local"
 else
-	if [[ "$gridsearch" -eq "1" ]]; then
-		TESTNAME="${TESTNAME}_gridsearch"
-		if [[ "$allow_failure" -eq "0" ]]; then
-			./omniopt \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_gridsearch" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--hide_ascii_plots
-			exit_code=$?
-		else
-			./omniopt \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_allow_failure_grid_search" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--gridsearch \
-				--hide_ascii_plots
-			exit_code=$?
-		fi
-	else
-		if [[ "$allow_failure" -eq "0" ]]; then
-			./omniopt \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--hide_ascii_plots
-			exit_code=$?
-		else
-			./omniopt \
-				--live_share \
-				--send_anonymized_usage_stats \
-				--partition $PARTITION \
-				--experiment_name "${TESTNAME}_allow_failure" \
-				--mem_gb=$mem_gb \
-				--time $time \
-				--worker_timeout=5 \
-				--max_eval $max_eval \
-				--num_parallel_jobs $num_parallel_jobs \
-				--gpus $NUM_GPUS \
-				--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0) \
-				--parameter int_param range -100 10 int \
-				--parameter float_param range -100 10 float \
-				--parameter choice_param choice 1,2,4,8,16,hallo \
-				--parameter int_param_two range -100 10 int \
-				--parameter fail_or_not choice "0,1" \
-				--follow \
-				--num_random_steps $num_random_steps \
-				--model $model \
-				--auto_exclude_defective_hosts \
-				--hide_ascii_plots
-			exit_code=$?
-		fi
-	fi
+    TESTNAME="${TESTNAME}"
 fi
 
-exit $exit_code
+if [[ "$gridsearch" -eq "1" ]]; then
+    PARTITION="${PARTITION}_gridsearch"
+else
+    PARTITION="${PARTITION}_nogridsearch"
+fi
+
+omniopt_cmd=$(build_omniopt_command)
+green_text "$omniopt_cmd"
+eval "$omniopt_cmd"
