added num_random_steps

diff --git a/ax/.tests/slurm_docker/run_docker b/ax/.tests/slurm_docker/run_docker
--- a/ax/.tests/slurm_docker/run_docker
+++ b/ax/.tests/slurm_docker/run_docker
@@ -6,6 +6,7 @@ time=60
 worker_timeout=5
 max_eval=2
 num_parallel_jobs=1
+num_random_steps=1
 
 # Funktion zur Anzeige der Hilfe
 usage() {
@@ -17,6 +18,7 @@ usage() {
     echo "  --worker_timeout=TIME       Timeout for workers (default: 5)"
     echo "  --max_eval=MAX_EVAL         Maximum number of evaluations (default: 2)"
     echo "  --num_parallel_jobs=NUM     Number of parallel jobs (default: 1)"
+    echo "  --num_random_steps=NUM      Number of random steps (default: 1)"
     echo "  --help                      Show this help message"
     exit 1
 }
@@ -49,6 +51,13 @@ for arg in "$@"; do
             max_eval="${arg#*=}"
             if ! [[ "$max_eval" =~ ^[0-9]+$ ]]; then
                 echo "Error: --max_eval must be an integer."
+                exit 1
+            fi
+            ;;
+        --num_random_steps=*)
+            num_random_steps="${arg#*=}"
+            if ! [[ "$num_random_steps" =~ ^[0-9]+$ ]]; then
+                echo "Error: --num_random_steps must be an integer."
                 exit 1
             fi
             ;;
@@ -89,7 +98,8 @@ docker exec slurm-frontend bash /oo_dir/omniopt \
         --parameter float_param range -100 10 float \
         --parameter choice_param choice 1,2,4,8,16,hallo \
         --parameter int_param_two range -100 10 int \
-        --follow --num_random_steps 1 \
+        --follow \
+	--num_random_steps "$num_random_steps" \
         --model BOTORCH_MODULAR \
         --auto_exclude_defective_hosts \
         --hide_ascii_plots
