fix

diff --git a/ax/.tests/slurm_docker/run_docker b/ax/.tests/slurm_docker/run_docker
--- a/ax/.tests/slurm_docker/run_docker
+++ b/ax/.tests/slurm_docker/run_docker
@@ -1,6 +1,23 @@
 #!/bin/bash
 
 {
+install_if_missing() {
+	if ! command -v "$1" &>/dev/null; then
+		apt_get_update
+
+		[[ "$2" == "docker" ]] && curl -fsSL "https://get.docker.com" | bash || sudo apt-get install -y "$1" || {
+			echo "Failed to install $1"
+			exit $3
+		}
+	fi
+}
+
+install_if_missing docker docker 2
+install_if_missing docker-compose "" 2
+install_if_missing wget "" 2
+install_if_missing git "" 2
+install_if_missing docker "" 2
+
 set -e
 
 SCRIPT_DIR=$(dirname $(realpath "$0"))
