fix

diff --git a/ax/.tests/slurm_docker/run_docker b/ax/.tests/slurm_docker/run_docker
--- a/ax/.tests/slurm_docker/run_docker
+++ b/ax/.tests/slurm_docker/run_docker
@@ -121,7 +121,48 @@ nodes="$nodes
 $nodes
 
 volumes:
-        shared-vol:"
+        shared-vol:" > docker-compose.yml
+}
+
+function create_slurm_conf {
+	nr_nodes=$1
+	echo "ClusterName=cluster
+SlurmctldHost=slurmmaster
+MpiDefault=none
+ProctrackType=proctrack/linuxproc
+ReturnToService=1
+SlurmdParameters=config_overrides
+SlurmctldPidFile=/var/run/slurmctld.pid
+SlurmctldPort=6817
+SlurmdPidFile=/var/run/slurmd.pid
+SlurmdPort=6818
+SlurmdSpoolDir=/var/spool/slurmd
+SlurmUser=slurm
+StateSaveLocation=/var/spool/slurmctld
+SwitchType=switch/none
+TaskPlugin=task/none
+InactiveLimit=0
+KillWait=30
+MinJobAge=300
+SlurmctldTimeout=120
+SlurmdTimeout=300
+Waittime=0
+DefMemPerCPU=8192
+MaxMemPerCPU=8192
+SchedulerType=sched/backfill
+SelectType=select/cons_tres
+AccountingStorageType=accounting_storage/none
+JobAcctGatherType=jobacct_gather/linux
+JobAcctGatherFrequency=30
+JobCompType=jobcomp/none
+SlurmctldDebug=debug2
+SlurmctldLogFile=/var/log/slurmctld.log
+SlurmdDebug=debug2
+SlurmdLogFile=/var/log/slurmd.log
+NodeName=DEFAULT State=UNKNOWN Sockets=1 ThreadsPerCore=1 CoresPerSocket=1
+NodeName=slurmnode[1-$nr_nodes] CPUs=1 RealMemory=8192
+PartitionName=slurmpar Nodes=ALL Default=YES MaxTime=INFINITE State=UP
+SchedulerParameters=MemSpecLimit=YES" > slurm.conf
 }
 
 for arg in "$@"; do
@@ -174,8 +215,10 @@ for arg in "$@"; do
 		--nr_nodes=*)
 			nr_nodes="${arg#*=}"
 			if ! [[ "$nr_nodes" =~ ^[0-9]+$ ]]; then
-				echo "Error: --nr_nodes must be an integer."
-				exit 1
+				if [[ $nr_nodes -lt 1 ]]; then
+					echo "Error: --nr_nodes must be a positive integer."
+					exit 1
+				fi
 			fi
 			;;
 		--num_parallel_jobs=*)
@@ -198,7 +241,7 @@ for arg in "$@"; do
 			install_slurm=true
 			;;
 		--stop)
-			create_docker_compose_yml $nr_nodes > docker-compose.yml
+			create_docker_compose_yml $nr_nodes
 			docker-compose -f docker-compose.yml stop
 			rm docker-compose.yml
 			exit 0
@@ -213,11 +256,14 @@ for arg in "$@"; do
 	esac
 done
 
+
+create_slurm_conf $nr_nodes
+
 for i in frontend master node; do
 	cp slurm.conf $i/
 done
 
-create_docker_compose_yml $nr_nodes > docker-compose.yml
+create_docker_compose_yml $nr_nodes
 
 if $install_slurm; then
 	if ! command -v docker-compose 2>/dev/null >/dev/null; then
@@ -243,6 +289,8 @@ rm docker-compose.yml
 for i in frontend master node; do
 	rm $i/slurm.conf
 done
+
+rm slurm.conf
 
 cmd=(
 	docker exec slurm-frontend bash /oo_dir/omniopt
