check if dispaly exists

diff --git a/ax/docker b/ax/docker
--- a/ax/docker
+++ b/ax/docker
@@ -111,10 +111,10 @@ function die {
 
 git rev-parse HEAD > git_hash
 
-sudo docker-compose build && sudo docker-compose up -d || {
-	echo "Failed to build container"
-	exit 1
-}
+#sudo docker-compose build && sudo docker-compose up -d || {
+#	echo "Failed to build container"
+#	exit 1
+#}
 
 rm git_hash
 
@@ -124,7 +124,11 @@ fi
 
 case "$ORIGINAL_ARGS" in
 	omniopt*|omniopt_plot*|omniopt_share*|omniopt_evaluate*)
-		docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+		if [[ -z $DISPLAY ]]; then
+			docker run -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+		else
+			docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+		fi
 		;;
 	*)
 		echo "Fehler: Das Argument beginnt nicht mit einem der gültigen Präfixe."
