fix

diff --git a/ax/docker b/ax/docker
--- a/ax/docker
+++ b/ax/docker
@@ -31,10 +31,15 @@ is_package_installed() {
 UPDATED_PACKAGES=0
 
 # Check if Docker is installed
-if ! command -v docker &>/dev/null; then
+if ! command -v docker &>/dev/null && command -v apt >/dev/null; then
+	if [[ ! -e /etc/apt/sources.list ]]; then
+		echo "/etc/apt/sources.list not found. Cannot continue. You must install docker manually."
+		exit 1
+	fi
 	echo "Docker not found. Installing Docker..."
-	# Enable non-free repository
+	echo "Enabling non-free repository..."
 	sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list
+	echo "Enabled! non-free repository."
 
 	# Update package lists
 	if [[ $UPDATED_PACKAGES == 0 ]]; then
