check for xhost as well

diff --git a/ax/docker b/ax/docker
--- a/ax/docker
+++ b/ax/docker
@@ -74,6 +74,24 @@ if ! command -v wget &>/dev/null; then
 	}
 fi
 
+if ! command -v xhost &>/dev/null; then
+	# Update package lists
+	if [[ $UPDATED_PACKAGES == 0 ]]; then
+		sudo apt update || {
+			echo "apt-get update failed. Are you online?"
+			exit 3
+		}
+
+		UPDATED_PACKAGES=1
+	fi
+
+	sudo apt-get install -y xhost || {
+		echo "sudo apt install -y xhost failed"
+		exit 4
+	}
+fi
+
+
 if ! command -v git &>/dev/null; then
 	# Update package lists
 	if [[ $UPDATED_PACKAGES == 0 ]]; then
@@ -127,7 +145,8 @@ case "$ORIGINAL_ARGS" in
 		if [[ -z $DISPLAY ]]; then
 			docker run -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
 		else
-			docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+			docker run --network=host --env DISPLAY=$DISPLAY --privileged --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -v /tmp/.X11-unix:/tmp/.X11-unix -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+			
 		fi
 		;;
 	*)
