fix

diff --git a/ax/evaluate-run b/ax/evaluate-run
--- a/ax/evaluate-run
+++ b/ax/evaluate-run
@@ -329,8 +329,8 @@ function list_option_for_job {
 
 			# Check if Perl and Text::CSV module are installed
 			if ! command -v perl &> /dev/null || ! perl -MText::CSV -e 1; then
-			    echo "Error: Perl or Text::CSV module not installed. Please install them to run this script."
-			    exit 1
+				echo "Error: Perl or Text::CSV module not installed. Please install them to run this script."
+				exit 1
 			fi
 
 			# Inline Perl script to extract and print "exit_code" column
