fix

diff --git a/ax/omniopt_share b/ax/omniopt_share
--- a/ax/omniopt_share
+++ b/ax/omniopt_share
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-source $SCRIPT_DIR/.shellscript_functions
+source "$SCRIPT_DIR/.shellscript_functions"
 
 function join_by {
 	local d=${1-} f=${2-}
@@ -43,21 +43,21 @@ experiment_name=$(echo "$RUN_DIR" | sed -e 's#/[0-9]*$##g' -e 's#.*/##')
 
 curl_options=()
 
-for available_file in $(ls $RUN_DIR); do 
+for available_file in $(ls "$RUN_DIR"); do 
 	available_file_param_name=$(echo "$available_file" | sed -e 's#\..*##')
-	if echo "$available_file" | egrep -i "\.(csv|txt)" 2>/dev/null > /dev/null; then
+	if echo "$available_file" | grep -Ei "\.(csv|txt)" 2>/dev/null > /dev/null; then
 		curl_options+=("-F" "$available_file_param_name=@$RUN_DIR/$available_file")
 	fi
 done
 
-for available_file in $(ls $RUN_DIR/state_files); do 
+for available_file in $(ls "$RUN_DIR/state_files"); do 
 	available_file_param_name=$(echo "$available_file" | sed -e 's#\..*##')
-	if echo "$available_file" | egrep -i "\.(csv|txt)" 2>/dev/null > /dev/null; then
+	if echo "$available_file" | grep -Ei "\.(csv|txt)" 2>/dev/null > /dev/null; then
 		curl_options+=("-F" "$available_file_param_name=@$RUN_DIR/$available_file")
 	fi
 done
 
-eval `resize`
+eval "$(resize)"
 user_id=$(whiptail --inputbox "By entering your name here you agree to make it public with this data? If you don't agree, cancel." 12 40  "$USER" --title "What should be your user name?" 3>&1 1>&2 2>&3)
 
 exitstatus=$?
@@ -71,7 +71,7 @@ fi
 BASEURL="https://imageseg.scads.de/omniax"
 
 if [[ -e "$HOME/.oo_base_url" ]]; then
-	BASEURL=$(cat $HOME/.oo_base_url)
+	BASEURL=$(cat "$HOME/.oo_base_url")
 	yellow_text "$HOME/.oo_base_url exists. Using base-url $BASEURL"
 fi
 
@@ -79,10 +79,10 @@ fi
 
 set -e
 url="$BASEURL/share.php?user_id=$user_id&experiment_name=$experiment_name"
-CURL_OUTPUT=$(curl -s "${curl_options[@]}" $url)
+CURL_OUTPUT=$(curl -s "${curl_options[@]}" "$url")
 exit_code=$?
 
-if [[ $exit_code -ne 0 ]] || echo "$CURL_OUTPUT" | grep "Error sharing the job." 2>&1 > /dev/null; then
+if [[ $exit_code -ne 0 ]] || echo "$CURL_OUTPUT" | grep "Error sharing the job." >/dev/null 2>&1 ; then
 	red_text "$CURL_OUTPUT"
 	if [[ $exit_code -ne 0 ]]; then
 		echo "Curling $url failed"
