fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -49,14 +49,12 @@ if ! command -v docker &>/dev/null; then
 		fi
 
 		# Update package lists
-		if [[ $UPDATED_PACKAGES == 0 ]]; then
-			sudo apt update || {
-				echo "apt-get update failed. Are you online?"
-				exit 2
-			}
+		sudo apt update || {
+			echo "apt-get update failed. Are you online?"
+			exit 2
+		}
 
-			UPDATED_PACKAGES=1
-		fi
+		UPDATED_PACKAGES=1
 
 
 		# Install Docker
