fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -36,12 +36,14 @@ if ! command -v docker &>/dev/null; then
 			exit 1
 		fi
 		echo "Docker not found. Installing Docker..."
-		echo "Enabling non-free repository..."
-		sudo sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list || {
-			echo "Could not edit /etc/apt/sources.list. Exiting."
-			exit 10
-		}
-		echo "Enabled! non-free repository."
+		if [[ -e /etc/apt/sources.list ]]; then
+			echo "Enabling non-free repository..."
+			sudo sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list || {
+				echo "Could not edit /etc/apt/sources.list. Exiting."
+				exit 10
+			}
+			echo "Enabled! non-free repository."
+		fi
 
 		# Update package lists
 		if [[ $UPDATED_PACKAGES == 0 ]]; then
@@ -56,7 +58,7 @@ if ! command -v docker &>/dev/null; then
 
 		# Install Docker
 		sudo apt install -y docker.io || {
-			echo "sudo apt install -y docker.io failed"
+			echo "sudo apt install -y docker.io failed. Try adding the repository for docker manually."
 			exit 3
 		}
 	else
