fix

diff --git a/ax/omniopt b/ax/omniopt
--- a/ax/omniopt
+++ b/ax/omniopt
@@ -50,14 +50,16 @@ already_sent_signal=
 kill_python_if_started () {
 	REASON=$1
 	re='^[0-9]+$'
-	if [[ $python_pid =~ $re ]] ; then
-		if [[ -z "$already_sent_signal" ]]; then
-			if ps auxf | grep $python_pid 2>/dev/null >/dev/null; then
-				already_sent_signal=1
-				echo -e "\nSending USR1 to $python_pid (python). Reason: $REASON"
-				kill -USR1 "$python_pid"
-			else
-				echo "Could not find $python_pid process" >&2
+	if [[ -z "$SLURM_JOB_ID" ]]; then
+		if [[ $python_pid =~ $re ]] ; then
+			if [[ -z "$already_sent_signal" ]]; then
+				if ps auxf | grep $python_pid 2>/dev/null >/dev/null; then
+					already_sent_signal=1
+					echo -e "\nSending USR1 to $python_pid (python). Reason: $REASON"
+					kill -USR1 "$python_pid"
+				else
+					echo "Could not find $python_pid process" >&2
+				fi
 			fi
 		fi
 	fi
