new version

diff --git a/ax/omniopt_plot b/ax/omniopt_plot
--- a/ax/omniopt_plot
+++ b/ax/omniopt_plot
@@ -121,100 +121,100 @@ args=("$@")
 k=0
 
 while [ $k -lt ${#args[@]} ]; do
-    arg="${args[k]}"
+	arg="${args[k]}"
 
-    case $arg in
-        --run_dir=*)
-            run_dir="${arg#*=}"
-            shift
-            ;;
+	case $arg in
+		--run_dir=*)
+			run_dir="${arg#*=}"
+			shift
+			;;
 
-        --run_dir)
-            k=$((k+1))
-            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
-                echo "Error: --run_dir requires a value"
-                exit 1
-            fi
-            run_dir="${args[k]}"
-            shift
-            shift
-            ;;
+		--run_dir)
+			k=$((k+1))
+			if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+				echo "Error: --run_dir requires a value"
+				exit 1
+			fi
+			run_dir="${args[k]}"
+			shift
+			shift
+			;;
 
-        --save_to_file=*)
-            _save_to_file="${arg#*=}"
-            shift
-            ;;
+		--save_to_file=*)
+			_save_to_file="${arg#*=}"
+			shift
+			;;
 
-        --save_to_file)
-            k=$((k+1))
-            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
-                echo "Error: --save_to_file requires a value"
-                exit 1
-            fi
-            _save_to_file="${args[k]}"
-            shift
-            shift
-            ;;
+		--save_to_file)
+			k=$((k+1))
+			if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+				echo "Error: --save_to_file requires a value"
+				exit 1
+			fi
+			_save_to_file="${args[k]}"
+			shift
+			shift
+			;;
 
-        --min=*)
-            min="${arg#*=}"
-            shift
-            ;;
+		--min=*)
+			min="${arg#*=}"
+			shift
+			;;
 
-        --min)
-            k=$((k+1))
-            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
-                echo "Error: --min requires a value"
-                exit 1
-            fi
-            min="${args[k]}"
-            shift
-            shift
-            ;;
+		--min)
+			k=$((k+1))
+			if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+				echo "Error: --min requires a value"
+				exit 1
+			fi
+			min="${args[k]}"
+			shift
+			shift
+			;;
 
-        --max=*)
-            max="${arg#*=}"
-            shift
-            ;;
+		--max=*)
+			max="${arg#*=}"
+			shift
+			;;
 
-        --max)
-            k=$((k+1))
-            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
-                echo "Error: --max requires a value"
-                exit 1
-            fi
-            max="${args[k]}"
-            shift
-            shift
-            ;;
+		--max)
+			k=$((k+1))
+			if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+				echo "Error: --max requires a value"
+				exit 1
+			fi
+			max="${args[k]}"
+			shift
+			shift
+			;;
 
-        --plot_type=*)
-            plot_type="${arg#*=}"
-            shift
-            ;;
+		--plot_type=*)
+			plot_type="${arg#*=}"
+			shift
+			;;
 
-        --plot_type)
-            k=$((k+1))
-            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
-                echo "Error: --plot_type requires a value"
-                exit 1
-            fi
-            plot_type="${args[k]}"
-            shift
-            shift
-            ;;
+		--plot_type)
+			k=$((k+1))
+			if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+				echo "Error: --plot_type requires a value"
+				exit 1
+			fi
+			plot_type="${args[k]}"
+			shift
+			shift
+			;;
 
-        --help|-h)
-            help=1
-            shift
-            ;;
+		--help|-h)
+			help=1
+			shift
+			;;
 
-        --debug)
-            set -x
-            shift
-            ;;
-    esac
-    k=$((k+1))
+		--debug)
+			set -x
+			shift
+			;;
+	esac
+	k=$((k+1))
 done
 
 if [[ ! " ${expected_plot_types[@]} " =~ " $plot_type " ]]; then
