fix

diff --git a/ax/omniopt b/ax/omniopt
--- a/ax/omniopt
+++ b/ax/omniopt
@@ -46,7 +46,8 @@ function calltracer () {
 }
 
 trap 'calltracer' ERR
-trap 'run_before_end' CONT
+trap 'kill_python_if_started' CONT
+trap 'kill_python_if_started' TERM
 
 minutes_to_hh_mm_ss() {
 	var=$1
@@ -420,6 +421,15 @@ python_pid=""
 JOB_START_TIME=$SLURM_JOB_START_TIME
 JOB_END_TIME=$SLURM_JOB_END_TIME
 
+kill_python_if_started () {
+	re='^[0-9]+$'
+	if ! [[ $python_pid =~ $re ]] ; then
+		echo "run_before_end error: Python-PID '$python_pid' is not a number" >&2
+	else
+		kill -USR1 "$python_pid"
+	fi
+}
+
 run_before_end () {
 	if command -v sbatch >/dev/null; then
 		# Weird solution, but signals never reached for some reason, and this... works?
@@ -428,12 +438,7 @@ run_before_end () {
 		if [ $sleep_time -gt 0 ]; then
 			sleep $sleep_time
 
-			re='^[0-9]+$'
-			if ! [[ $python_pid =~ $re ]] ; then
-				echo "run_before_end error: Python-PID '$python_pid' is not a number"
-			else
-				kill -USR1 "$python_pid"
-			fi
+			kill_python_if_started
 		else
 			echo "It is recommended that you run this in a slurm job."
 		fi
@@ -516,6 +521,7 @@ if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
 
 	set +e
 	python3 $SCRIPT_DIR/.omniopt.py $args_string
+	python_pid=$!
 	set -e
 
 	EXIT_CODE=$?
