fix

diff --git a/ax/omniopt b/ax/omniopt
--- a/ax/omniopt
+++ b/ax/omniopt
@@ -506,14 +506,19 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
 if [ -n "${SLURM_JOB_ID:-}" ] ; then
 	set +e
-	SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
-	SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
-	set -e
+	if command -v scontrol 2>/dev/null >/dev/null; then
+		SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
+		SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
+		set -e
 
-	if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
-		SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
+		if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
+			SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
+		else
+			echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
+		fi
 	else
-		echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
+		red_text "scontrol not found. Unsetting SLURM_JOB_ID"
+		unset SLURM_JOB_ID
 	fi
 fi
 
