fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -31,6 +31,22 @@ is_package_installed() {
 
 UPDATED_PACKAGES=0
 
+function apt_get_update () {
+	if command -v apt >/dev/null; then
+		if [[ $UPDATED_PACKAGES == 0 ]]; then
+			sudo apt update || {
+				echo "apt-get update failed. Are you online?"
+				exit 2
+			}
+
+			UPDATED_PACKAGES=1
+		fi
+	else
+		echo "apt is not installed. You need to be on debian for auto-installing packages. Please install it manually."
+		exit 10
+	fi
+}
+
 # Check if Docker is installed
 if ! command -v docker &>/dev/null; then
 	if command -v apt >/dev/null; then
@@ -48,13 +64,8 @@ if ! command -v docker &>/dev/null; then
 			echo "Enabled! non-free repository."
 		fi
 
-		# Update package lists
-		sudo apt update || {
-			echo "apt-get update failed. Are you online?"
-			exit 2
-		}
-
-		UPDATED_PACKAGES=1
+		UPDATED_PACKAGES=0
+		apt_get_update
 
 
 		# Install Docker
@@ -69,15 +80,7 @@ if ! command -v docker &>/dev/null; then
 fi
 
 if ! command -v wget &>/dev/null; then
-	# Update package lists
-	if [[ $UPDATED_PACKAGES == 0 ]]; then
-		sudo apt update || {
-			echo "apt-get update failed. Are you online?"
-			exit 3
-		}
-
-		UPDATED_PACKAGES=1
-	fi
+	apt_get_update
 
 	sudo apt-get install -y wget || {
 		echo "sudo apt install -y wget failed"
@@ -86,15 +89,7 @@ if ! command -v wget &>/dev/null; then
 fi
 
 if ! command -v xhost &>/dev/null; then
-	# Update package lists
-	if [[ $UPDATED_PACKAGES == 0 ]]; then
-		sudo apt update || {
-			echo "apt-get update failed. Are you online?"
-			exit 3
-		}
-
-		UPDATED_PACKAGES=1
-	fi
+	apt_get_update
 
 	sudo apt-get install -y xhost || {
 		echo "sudo apt install -y xhost failed"
@@ -104,15 +99,7 @@ fi
 
 
 if ! command -v git &>/dev/null; then
-	# Update package lists
-	if [[ $UPDATED_PACKAGES == 0 ]]; then
-		sudo apt update || {
-			echo "apt-get update failed. Are you online?"
-			exit 3
-		}
-
-		UPDATED_PACKAGES=1
-	fi
+	apt_get_update
 
 	sudo apt-get install -y git || {
 		echo "sudo apt install -y git failed"
@@ -124,8 +111,6 @@ if ! command -v docker &>/dev/null; then
 	echo "docker not found. Cannot continue."
 	exit 5
 fi
-
-
 
 echo "=== Current git hash before auto-pulling ==="
 git rev-parse HEAD
