fix

diff --git a/ax/omniopt_share b/ax/omniopt_share
--- a/ax/omniopt_share
+++ b/ax/omniopt_share
@@ -59,4 +59,9 @@ else
 fi
 
 set -e
-curl ${curl_params} "https://imageseg.scads.de/omniax/share.php?user_id=$user_id&experiment_name=$experiment_name"
+url="https://imageseg.scads.de/omniax/share.php?user_id=$user_id&experiment_name=$experiment_name"
+curl ${curl_params} $url
+
+if [[ $? -ne 0 ]]; then
+	echo "Curling $url failed"
+fi
