fix

diff --git a/ax/omniopt b/ax/omniopt
--- a/ax/omniopt
+++ b/ax/omniopt
@@ -45,9 +45,26 @@ function calltracer () {
         caller
 }
 
+kill_python_if_started () {
+	REASON=$1
+	re='^[0-9]+$'
+	if ! [[ $python_pid =~ $re ]] ; then
+		echo "run_before_end error: Python-PID '$python_pid' is not a number" >&2
+	else
+		echo "Sending USR1 to $python_pid (python). Reason: $REASON"
+		kill -USR1 "$python_pid"
+	fi
+}
+
 trap 'calltracer' ERR
-trap 'kill_python_if_started' CONT
-trap 'kill_python_if_started' TERM
+trap 'kill_python_if_started CONT' CONT
+trap 'kill_python_if_started TERM' TERM
+
+for i in $(kill -l 2>&1 | sed -e 's#[0-9][0-9]*\s*)##g'); do
+	if [[ "$i" != "ERR" ]] && [[ "$i" != "CONT" ]] && [[ "$i" != "TERM" ]]; then
+		trap "kill_python_if_started $i" $i
+	fi
+done
 
 minutes_to_hh_mm_ss() {
 	var=$1
@@ -421,15 +438,6 @@ python_pid=""
 JOB_START_TIME=$SLURM_JOB_START_TIME
 JOB_END_TIME=$SLURM_JOB_END_TIME
 
-kill_python_if_started () {
-	re='^[0-9]+$'
-	if ! [[ $python_pid =~ $re ]] ; then
-		echo "run_before_end error: Python-PID '$python_pid' is not a number" >&2
-	else
-		kill -USR1 "$python_pid"
-	fi
-}
-
 run_before_end () {
 	if command -v sbatch >/dev/null; then
 		# Weird solution, but signals never reached for some reason, and this... works?
@@ -438,7 +446,7 @@ run_before_end () {
 		if [ $sleep_time -gt 0 ]; then
 			sleep $sleep_time
 
-			kill_python_if_started
+			kill_python_if_started "Timeout"
 		else
 			echo "It is recommended that you run this in a slurm job."
 		fi
