larger language icons

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -142,15 +142,28 @@ mkdir -p .logs
 
 git rev-parse HEAD > git_hash
 
-docker-compose build --build-arg GetMyUsername=`whoami` || {
-	echo "Failed composing container"
-	exit 1
-}
+if groups | grep docker 2>/dev/null >/dev/null; then
+	docker-compose build --build-arg GetMyUsername=`whoami` || {
+		echo "Failed composing container"
+		exit 1
+	}
 
-docker-compose up -d || {
-	echo "Failed to build container"
-	exit 1
-}
+	docker-compose up -d || {
+		echo "Failed to build container"
+		exit 1
+	}
+else
+	echo "Your user is not in the group docker. Thus, docker-compose builds need sudo. Enter your password, please."
+	sudo docker-compose build --build-arg GetMyUsername=`whoami` || {
+		echo "Failed composing container"
+		exit 1
+	}
+
+	sudo docker-compose up -d || {
+		echo "Failed to build container"
+		exit 1
+	}
+fi
 
 rm git_hash
 
