exit code checker

diff --git a/ax/omniopt b/ax/omniopt
--- a/ax/omniopt
+++ b/ax/omniopt
@@ -868,4 +868,10 @@ else
 fi
 
 echo "Runtime: $(displaytime $SECONDS)"
-exit $exit_code
+
+if [[ "$exit_code" =~ ^[0-9]+$ ]]; then
+	exit $exit_code
+else
+	echo "Invalid exit-code $exit_code detected!"
+	exit 1
+fi
