fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -29,35 +29,40 @@ is_package_installed() {
 UPDATED_PACKAGES=0
 
 # Check if Docker is installed
-if ! command -v docker &>/dev/null && command -v apt >/dev/null; then
-	if [[ ! -e /etc/apt/sources.list ]]; then
-		echo "/etc/apt/sources.list not found. Cannot continue. You must install docker manually."
-		exit 1
-	fi
-	echo "Docker not found. Installing Docker..."
-	echo "Enabling non-free repository..."
-	sudo sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list || {
-		echo "Could not edit /etc/apt/sources.list. Exiting."
-		exit 10
-	}
-	echo "Enabled! non-free repository."
-
-	# Update package lists
-	if [[ $UPDATED_PACKAGES == 0 ]]; then
-		sudo apt update || {
-			echo "apt-get update failed. Are you online?"
-			exit 2
+if ! command -v docker &>/dev/null; then
+	if command -v apt >/dev/null; then
+		if [[ ! -e /etc/apt/sources.list ]]; then
+			echo "/etc/apt/sources.list not found. Cannot continue. You must install docker manually."
+			exit 1
+		fi
+		echo "Docker not found. Installing Docker..."
+		echo "Enabling non-free repository..."
+		sudo sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list || {
+			echo "Could not edit /etc/apt/sources.list. Exiting."
+			exit 10
 		}
+		echo "Enabled! non-free repository."
 
-		UPDATED_PACKAGES=1
+		# Update package lists
+		if [[ $UPDATED_PACKAGES == 0 ]]; then
+			sudo apt update || {
+				echo "apt-get update failed. Are you online?"
+				exit 2
+			}
+
+			UPDATED_PACKAGES=1
+		fi
+
+
+		# Install Docker
+		sudo apt install -y docker.io || {
+			echo "sudo apt install -y docker.io failed"
+			exit 3
+		}
+	else
+		echo "Can only auto-install docker on debian systems. You need to install docker yourself on your distro."
+		exit 11
 	fi
-
-
-	# Install Docker
-	sudo apt install -y docker.io || {
-		echo "sudo apt install -y docker.io failed"
-		exit 3
-	}
 fi
 
 if ! command -v wget &>/dev/null; then
