fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -132,7 +132,12 @@ mkdir -p .logs
 
 git rev-parse HEAD > git_hash
 
-sudo docker-compose build --build-arg GetMyUsername=`whoami` && sudo docker-compose up -d || {
+sudo docker-compose build --build-arg GetMyUsername=`whoami` || {
+	echo "Failed composing container"
+	exit 1
+}
+
+sudo docker-compose up -d || {
 	echo "Failed to build container"
 	exit 1
 }
@@ -146,9 +151,16 @@ fi
 case "$ORIGINAL_ARGS" in
 	omniopt*|omniopt_plot*|omniopt_share*|omniopt_evaluate*|./.tests/*)
 		if [[ -z $DISPLAY ]]; then
-			docker run -v ${pwd}/.logs:/var/opt/omniopt/.logs:rw -v ${pwd}/runs:/var/opt/omniopt/runs:rw -i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+			docker run \
+				-v $(pwd)/.logs:/var/opt/omniopt/.logs:rw \
+				-v $(pwd)/runs:/var/opt/omniopt/runs:rw \
+				-i -t --rm \
+				ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
 		else
-			docker run -v ${pwd}/.logs:/var/opt/omniopt/.logs:rw -v ${pwd}/runs:/var/opt/omniopt/runs:rw \
+			set -x
+			docker run \
+				-v $(pwd)/.logs:/var/opt/omniopt/.logs:rw \
+				-v $(pwd)/runs:/var/opt/omniopt/runs:rw \
 				--user=$(id -u) \
 				--env="DISPLAY" \
 				--volume="/etc/group:/etc/group:ro" \
@@ -156,7 +168,8 @@ case "$ORIGINAL_ARGS" in
 				--volume="/etc/shadow:/etc/shadow:ro" \
 				--volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
 				--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
-				-i -t ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
+				-i -t --rm ax_omniopt2 \
+				bash /var/opt/omniopt/$ORIGINAL_ARGS
 		fi
 		;;
 	*)
