check earlier for wrong plot_types

diff --git a/ax/omniopt_plot b/ax/omniopt_plot
--- a/ax/omniopt_plot
+++ b/ax/omniopt_plot
@@ -208,8 +208,14 @@ while [ $k -lt ${#args[@]} ]; do
 done
 
 if [[ ! " ${expected_plot_types[@]} " =~ " $plot_type " ]]; then
-    echo "Wrong plot type: $plot_type, but got $plot_type"
-    exit 99
+	# Verbinden Sie die Elemente des Arrays zu einem mit "," getrennten String
+	joined_plot_types=$(printf "%s, " "${expected_plot_types[@]}")
+
+	# Entfernen Sie das letzte "," vom gejointen String
+	joined_plot_types=${joined_plot_types%, }
+
+	echo "Invalid plot type $plot_type, valid plot types: $joined_plot_types"
+	exit 99
 fi
 
 if [[ "$plot_type" == "default" ]]; then
