fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -66,6 +66,15 @@ if ! command -v docker &>/dev/null; then
 	fi
 fi
 
+if ! command -v docker-compose &>/dev/null; then
+	apt_get_update
+
+	sudo apt-get install -y docker-compose|| {
+		echo "sudo apt install -y docker-compose failed"
+		exit 3
+	}
+fi
+
 if ! command -v wget &>/dev/null; then
 	apt_get_update
 
