fix

diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -31,10 +31,6 @@ while [[ "$#" -gt 0 ]]; do
 	shift
 done
 
-is_package_installed() {
-	dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -c "ok installed"
-}
-
 UPDATED_PACKAGES=0
 
 function apt_get_update () {
@@ -54,12 +50,14 @@ function apt_get_update () {
 }
 
 install_if_missing() {
-    if ! command -v "$1" &>/dev/null; then
-        [[ "$2" == "docker" ]] && curl -fsSL "https://get.docker.com" | bash || sudo apt-get install -y "$1" || {
-            echo "Failed to install $1"
-            exit $3
-        }
-    fi
+	if ! command -v "$1" &>/dev/null; then
+		apt_get_update
+
+		[[ "$2" == "docker" ]] && curl -fsSL "https://get.docker.com" | bash || sudo apt-get install -y "$1" || {
+			echo "Failed to install $1"
+			exit $3
+		}
+	fi
 }
 
 install_if_missing docker docker 2
