Squashed commit for range v2.0.153 to v2.0.154

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,63 +3,49 @@ name: CI
 on:
   push:
     branches:
-      - main
+      - '**'
   pull_request:
     branches:
-      - main
+      - '**'
 
 jobs:
-  build:
-    #runs-on: ubuntu-latest 
-    runs-on: ${{ matrix.os }}
+  Linter:
     strategy:
-      matrix:
-        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04] #, macos-14]
+      fail-fast: true
+    runs-on: "ubuntu-latest"
+
+    permissions:
+      contents: write
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Cache pip packages
-      uses: actions/cache@v3
+    - name: Cache Python packages
+      uses: actions/cache@v4
       with:
         path: |
-          ~/.cache/pip
-          ~/.local/share/virtualenvs
-        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          $HOME/.cache/pip
+          $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
+        key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
         restore-keys: |
-          ${{ runner.os }}-pip-
-    - name: omniopt-venv
-      uses: actions/cache@v3
-      with:
-        path: $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')
-        key: ${{ runner.os }}-omniax-${{ hashFiles('**/requirements.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-omniax-
-    - name: omniopt-test-venv
-      uses: actions/cache@v3
-      with:
-        path: $HOME/.omniopt_test_install_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')
-        key: ${{ runner.os }}-omniax-test-${{ hashFiles('**/requirements.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-omniax-test
+          ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+
+    - name: Checkout code
+      uses: actions/checkout@v4
+
     - name: Install dependencies
       run: |
         if [[ $RUNNER_OS == 'Linux' ]]; then
           if grep -q '^ID=ubuntu' /etc/os-release; then
-            sudo apt-get update
-            sudo apt-get install -y xterm whiptail python3-dev
-          elif grep -q '^ID=centos' /etc/os-release; then
-            sudo yum install -y xterm whiptail python3-devel
-          elif grep -q '^ID=debian' /etc/os-release; then
-            sudo apt-get update
-            sudo apt-get install -y xterm whiptail python3-dev
+            sudo apt-get update || sudo apt-get update || sudo apt-get update
+            sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
+            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
+            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          else
+            echo "Invalid OS for pipeline. Only works with Ubuntu"
+            exit 1
           fi
         else
-          echo "Detected Mac"
-          brew install postgresql
-          brew install xterm
-          brew install newt
+            echo "Invalid OS detected"
+            exit 2
         fi
     - name: Creating virtualenv
       run: |
@@ -69,36 +55,239 @@ jobs:
         if command -v brew; then
           pip install psycopg2-binary
         fi
-    - name: Upgrading pip
+    - name: Installing stuff...
       run: |
         source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
         pip install --no-cache-dir --upgrade pip
-    - name: Installing setuptools
-      run: |
-        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
         pip install --no-cache-dir setuptools
-    - name: Upgrading wheel
-      run: |
-        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
         pip install --no-cache-dir pip wheel
-    - name: Install multidict
-      run: |
-        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
         pip install --no-cache-dir multidict
     - name: main test script
       run: |
-        ./ax/.tests/main --num_random_steps=1 --max_eval=2 --exit_on_first_error
+        ./ax/.tests/linter
+
+  docker-test:
+    needs: [Linter, markdown-lint, todo-to-issue]
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: true
+      matrix:
+        os: [ubuntu-24.04] #, ubuntu-22.04, ubuntu-20.04] #, macos-14]
+
+    steps:
+    - name: Cache Python packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          $HOME/.cache/pip
+          $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
+        key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Install dependencies
+      run: |
+        if [[ $RUNNER_OS == 'Linux' ]]; then
+          if grep -q '^ID=ubuntu' /etc/os-release; then
+            sudo apt-get update || sudo apt-get update || sudo apt-get update
+            sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
+            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
+            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          else
+            echo "Invalid OS for pipeline. Only works with Ubuntu"
+            exit 1
+          fi
+        else
+            echo "Invalid OS detected"
+            exit 2
+        fi
+    - name: Creating virtualenv
+      run: |
+        python3 -mvenv $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')
+        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
+
+        if command -v brew; then
+          pip install psycopg2-binary
+        fi
+    - name: Installing stuff...
+      run: |
+        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
+        pip install --no-cache-dir --upgrade pip
+        pip install --no-cache-dir setuptools
+        pip install --no-cache-dir pip wheel
+        pip install --no-cache-dir multidict
+
+    - name: main test script
+      run: |
+        ./ax/omniopt_docker .tests/main --num_random_steps=1 --max_eval=2 --exit_on_first_error --superquick
+
+  main-test:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: true
+      matrix:
+        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04] #, macos-14]
+
+    steps:
+    - name: Cache Python packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          $HOME/.cache/pip
+          $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
+        key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Install dependencies
+      run: |
+        if [[ $RUNNER_OS == 'Linux' ]]; then
+          if grep -q '^ID=ubuntu' /etc/os-release; then
+            sudo apt-get update || sudo apt-get update || sudo apt-get update
+            sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
+            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
+            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          else
+            echo "Invalid OS for pipeline. Only works with Ubuntu"
+            exit 1
+          fi
+        else
+            echo "Invalid OS detected"
+            exit 2
+        fi
+    - name: Creating virtualenv
+      run: |
+        python3 -mvenv $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')
+        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
+
+        if command -v brew; then
+          pip install psycopg2-binary
+        fi
+    - name: Installing stuff...
+      run: |
+        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
+        pip install --no-cache-dir --upgrade pip
+        pip install --no-cache-dir setuptools
+        pip install --no-cache-dir pip wheel
+        pip install --no-cache-dir multidict
+
+    - name: main test script
+      run: |
+        ./ax/.tests/main --num_random_steps=1 --max_eval=2 --exit_on_first_error --run_with_coverage
+    - name: Upload coverage to Coveralls
+      uses: coverallsapp/github-action@v2
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        flag-name: run-${{ join(matrix.*, '-') }}
+        parallel: true
+    - uses: release-drafter/release-drafter@v5
+      with:
+          config-name: release-drafter.yml
+      #   disable-autolabeler: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
     - name: Create a new version
       if: ${{ success() }}
       run: |
-        echo "Creating new version..."
+        echo "Creating new version"
         git tag v2.0.${{ github.run_number }} || true
         git push origin --tags || true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    - uses: "marvinpinto/action-automatic-releases@latest"
+
+    - name: Copy coverage files
+      run: |
+        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+        git config --global user.name "${{ github.actor }}"
+
+        git clone --depth 1 https://NormanTUD:${{ secrets.PRIVKEY }}@github.com/NormanTUD/omniopt2.github.io.git
+
+        mkdir -p omniopt2.github.io/coverage_reports/${{ github.run_number }}/${{ matrix.os }}
+
+        cp -r ./ax/htmlcov/* omniopt2.github.io/coverage_reports/${{ github.run_number }}/${{ matrix.os }}
+
+        cd omniopt2.github.io
+
+        git config pull.rebase false
+
+        git pull
+
+        base_dir="coverage_reports"
+        index_file="index.html"
+
+        cp "$index_file" "${index_file}.bak"
+
+        echo "<html><body>" > "$index_file"
+
+        for run_dir in $(ls -d "$base_dir"/* | tac); do
+          run_number=$(basename "$run_dir")
+
+          echo "<h1>Run #$run_number</h1>" >> "$index_file"
+          echo "<table border='1'>" >> "$index_file"
+          echo "<tr>" >> "$index_file"
+
+          for os_dir in "$run_dir"/*; do
+            os=$(basename "$os_dir")
+
+            report_link="coverage_reports/$run_number/$os/index.html"
+
+            echo "<td><a href='$report_link'>$os</a></td>" >> "$index_file"
+          done
+
+          echo "</tr>" >> "$index_file"
+          echo "</table>" >> "$index_file"
+        done
+
+        echo "</body></html>" >> "$index_file"
+
+        git add "$index_file"
+
+        rm "${index_file}.bak"
+
+        git add .
+        git commit -am "Add coverage report from run ${{ github.run_number }}/${{ matrix.os }} and update index.html"
+        git pull
+        git push origin main
+
+        cd ..
+
+        rm -rf omniopt2.github.io
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  markdown-lint:
+    strategy:
+      fail-fast: true
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Run markdownlint
+        run: npm install -g markdownlint-cli && markdownlint '**/*.md'
+
+  todo-to-issue:
+    strategy:
+      fail-fast: true
+    runs-on: "ubuntu-latest"
+    steps:
+      - uses: "actions/checkout@v4"
+      - name: "TODO to Issue"
+        uses: "alstr/todo-to-issue-action@v5"
+
+  covering-uploader:
+    needs: [main-test, Linter, markdown-lint, todo-to-issue]
+    if: ${{ success() }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Coveralls Finished
+      uses: coverallsapp/github-action@v2
       with:
-        repo_token: "${{ secrets.GITHUB_TOKEN }}"
-        automatic_release_tag: "latest"
-        prerelease: false
-        title: "Development Build v2.0.${{ github.run_number }}"
+        parallel-finished: true
+        carryforward: "run-1,run-2,run-3"
diff --git a/ax/.tests/optimization_example b/ax/.tests/optimization_example
--- a/ax/.tests/optimization_example
+++ b/ax/.tests/optimization_example
@@ -1,5 +1,20 @@
 #!/bin/bash
 
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+CYAN='\033[0;36m'
+MAGENTA='\033[0;35m'
+NC='\033[0m'
+
+function set_debug {
+	trap 'echo -e "${CYAN}$(date +"%Y-%m-%d %H:%M:%S")${NC} ${MAGENTA}| Line: $LINENO ${NC}${YELLOW}-> ${NC}${BLUE}[DEBUG]${NC} ${GREEN}$BASH_COMMAND${NC}"' DEBUG
+}
+
+function unset_debug {
+	trap - DEBUG
+}
+
 function echoerr() {
         echo "$@" 1>&2
 }
@@ -23,35 +38,47 @@ function help () {
         echo "  --int_param_two=(INT)"
         echo "  --float_param=(FLOAT)"
         echo "  --choice_param=(STRING)                            Must be 1, 2, 4, 8, 16 or hallo"
-        echo "  --fail_or_not=0|1                                         Whether to fail or not"
-        echo "  --help                                             this help"
-        echo "  --debug                                            Enables debug mode (set -x)"
+        echo "  --fixed_param                                      Will be ignored"
+        echo "  --fail_or_not=0|1                                  Whether to fail or not"
+        echo "  --help                                             This help"
+        echo "  --debug                                            Enables debug mode"
         exit $1
 }
 export int_param=
 export int_param_two=
 export float_param=
 export choice_param=
+export fixed_param=
 export fail_or_not=0
 
-for i in $@; do
+for i in "$@"; do
         case $i in
+                --fixed_param=*)
+			fixed_param="${i#*=}"
+                        shift
+                        ;;
+
+
                 --int_param_two=*)
                         int_param_two="${i#*=}"
                         shift
                         ;;
+
                 --int_param=*)
                         int_param="${i#*=}"
                         shift
                         ;;
+
                 --float_param=*)
                         float_param="${i#*=}"
                         shift
                         ;;
+
                 --choice_param=*)
                         choice_param="${i#*=}"
                         shift
                         ;;
+
                 --fail_or_not=*)
                         new_param="${i#*=}"
 			if [[ "$new_param" == *"1"* ]]; then
@@ -59,12 +86,15 @@ for i in $@; do
 			fi
                         shift
                         ;;
+
                 -h|--help)
                         help 0
                         ;;
+
                 --debug)
-                        set -x
+			set_debug
                         ;;
+
                 *)
                         red_text "Unknown parameter $i" >&2
                         help 1
@@ -142,7 +172,6 @@ sub shekel {
 
         return $outer_sum;
 }
-
 
 print qq#RESULT: #.shekel(@ARGV).qq#\n#;
 ' -- $int_param $choice_param $float_param $int_param_two
diff --git a/ax/.tests/plots b/ax/.tests/plots
--- a/ax/.tests/plots
+++ b/ax/.tests/plots
@@ -1,11 +1,42 @@
 #!/bin/bash
+
 {
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+CYAN='\033[0;36m'
+MAGENTA='\033[0;35m'
+NC='\033[0m'
+
+function echoerr() {
+        echo "$@" 1>&2
+}
+
+function yellow_text {
+        echoerr -ne "\e\033[0;33m$1\e[0m"
+}
+
+function red_text {
+        echoerr -ne "\e[31m$1\e[0m"
+}
+
+function green_text {
+        echoerr -ne "\e\033[0;32m$1\e[0m"
+}
+
+function set_debug {
+	trap 'echo -e "${CYAN}$(date +"%Y-%m-%d %H:%M:%S")${NC} ${MAGENTA}| Line: $LINENO ${NC}${YELLOW}-> ${NC}${BLUE}[DEBUG]${NC} ${GREEN}$BASH_COMMAND${NC}"' DEBUG
+}
+
+function unset_debug {
+	trap - DEBUG
+}
+
 export PRINT_SEPERATOR=""
 export NO_RUNTIME=1
 export NO_NO_RESULT_ERROR=1
-export DONT_INSTALL_MODULES=1
-export DONT_SHOW_DONT_INSTALL_MESSAGE=1
 export PLOT_TESTS=1
+export DONT_SHOW_DONT_INSTALL_MESSAGE=1
 
 test_types_regex=""
 
@@ -41,37 +72,6 @@ function green_reset_line {
 	green_text "$1"
 }
 
-generate_progress_bar() {
-	local current_progress=$1
-	local total_progress=$2
-
-	# Überprüfen, ob die Eingaben gültige positive Ganzzahlen sind
-	if ! [[ "$current_progress" =~ ^[0-9]+$ ]] || ! [[ "$total_progress" =~ ^[0-9]+$ ]]; then
-		echo "Fehler: Beide Parameter müssen positive Ganzzahlen sein, sind $current_progress/$total_progress." >&2
-		return 1
-	fi
-
-	# Überprüfen, ob der aktuelle Fortschritt den Gesamtfortschritt nicht überschreitet
-	if [ "$current_progress" -gt "$total_progress" ]; then
-		echo "Fehler: Der aktuelle Fortschritt darf den Gesamtfortschritt nicht überschreiten ($current_progress/$total_progress)." >&2
-		return 1
-	fi
-
-	local bar_length=30
-	local filled_length=$((bar_length * current_progress / total_progress))
-	local empty_length=$((bar_length - filled_length))
-
-	local bar=""
-	for ((i = 0; i < filled_length; i++)); do
-		bar="${bar}#"
-	done
-	for ((i = 0; i < empty_length; i++)); do
-		bar="${bar} "
-	done
-
-	echo "[${bar}] ($current_progress/$total_progress)"
-}
-
 
 help=0
 
@@ -94,8 +94,18 @@ while [ $k -lt ${#args[@]} ]; do
 			shift
 			;;
 
+		--run_with_coverage)
+			echo "Using *coverage run -p* instead of *python3*"
+			export RUN_WITH_COVERAGE=1
+			;;
+
 		--test_types=*)
 			test_types_regex="${arg#*=}"
+			shift
+			;;
+
+		--exit_on_first_error)
+			exit_on_first_error=1
 			shift
 			;;
 
@@ -105,7 +115,7 @@ while [ $k -lt ${#args[@]} ]; do
 			;;
 
 		--debug)
-			set -x
+			set_debug
 			shift
 			;;
 	esac
@@ -114,36 +124,35 @@ done
 
 if [[ "$help" -eq "1" ]]; then
 	echo ".tests/plots:"
-	echo "--keep_tmp                            Keep tmp files"
-	echo "--test_types=a|b|c                    A regex for filetypes to be tested"
-	echo "--quick                               Disables some slow tests"
+	echo "--keep_tmp                                           Keep tmp files"
+	echo "--test_types=a|b|c                                   A regex for filetypes to be tested"
+	echo "--quick                                              Disables some slow tests"
+	echo "--exit_on_first_error                                Exits on first error"
+	echo "--run_with_coverage                                  Run every python script with coverage"
 	exit 0
 fi
 
 errors=()
 
-function join_by {
-	local d=${1-} f=${2-}
-	if shift 2; then
-		printf %s "$f" "${@/#/$d}"
-	fi
-}
-
-function echoerr() {
-        echo "$@" 1>&2
-}
-
-function yellow_text {
-        echoerr -ne "\e\033[0;33m$1\e[0m"
-}
-
-function red_text {
-        echoerr -ne "\e[31m$1\e[0m"
-}
-
-function green_text {
-        echoerr -ne "\e\033[0;32m$1\e[0m"
-}
+#for i in .omniopt_plot_*.py; do
+#	green_reset_line "Testing the exit code of $i outside of the bash wrapper (should be 1 or 16)..."
+#	if [[ -z $RUN_WITH_COVERAGE ]]; then
+#		python3 $i 2>/dev/null >/dev/null
+#		exit_code=$?
+#	else
+#		coverage run -p $i 2>/dev/null >/dev/null
+#		exit_code=$?
+#	fi
+#	green_reset_line "$i exited with $exit_code"
+#	if [[ $exit_code -ne 16 ]] && [[ $exit_code -ne 1 ]]; then
+#		red_text "$i does not exit with code 1 or 16 outside of bash (has: $exit_code)\n"
+#		errors+=("$i does not exit with code 1 or 16 outside of bash (has: $exit_code)")
+#
+#		if [[ $exit_on_first_error ]]; then
+#			exit 1
+#		fi
+#	fi
+#done
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
@@ -151,6 +160,14 @@ cd $SCRIPT_DIR
 
 cd ..
 
+source .shellscript_functions
+
+function join_by {
+	local d=${1-} f=${2-}
+	if shift 2; then
+		printf %s "$f" "${@/#/$d}"
+	fi
+}
 
 expected_plot_types=()
 
@@ -214,24 +231,29 @@ for projectname in "${test_projects[@]}"; do
 				if [[ $ALL_FILES_THERE -ne 0 ]]; then
 					_command="bash omniopt_plot --run_dir=$run_dir --save_to_file=$this_img --plot_type=$possible_plot_type"
 
-					_commands+=("$_command")
+					allowed_plot_types=("cpu_ram_usage" "get_next_trials")
 
-					if [[ $quick -eq 0 ]]; then
-						has_min=$(cat ".omniopt_plot_$possible_plot_type.py" | grep "add.argument..--min" | wc -l)
-						has_max=$(cat ".omniopt_plot_$possible_plot_type.py" | grep "add.argument..--max" | wc -l)
+					if [[ $projectname == "maximize_test" ]] && [[ " ${allowed_plot_types[@]} " =~ " ${possible_plot_type} " ]]; then
+						true
+					else
+						_commands+=("$_command")
 
+						if [[ $quick -eq 0 ]]; then
+							has_min=$(cat ".omniopt_plot_$possible_plot_type.py" | grep "add.argument..--min" | wc -l)
+							has_max=$(cat ".omniopt_plot_$possible_plot_type.py" | grep "add.argument..--max" | wc -l)
 
-						if [[ $has_min -gt 0 ]] && [[ $has_max -gt 0 ]]; then
-							_commands+=("$_command --min=-99999999999999999999999999999999999999999999999999999999999 --max=99999999999999999999999999999999999999999999999999999999999")
-						elif [[ $has_min -gt 0 ]]; then
-							_commands+=("$_command --min=-99999999999999999999999999999999999999999999999999999999999")
-						elif [[ $has_max -gt 0 ]]; then
-							_commands+=("$_command --max=99999999999999999999999999999999999999999999999999999999999")
+							if [[ $has_min -gt 0 ]] && [[ $has_max -gt 0 ]]; then
+								_commands+=("$_command --min=-99999999999999999999999999999999999999999999999999999999999 --max=99999999999999999999999999999999999999999999999999999999999")
+							elif [[ $has_min -gt 0 ]]; then
+								_commands+=("$_command --min=-99999999999999999999999999999999999999999999999999999999999")
+							elif [[ $has_max -gt 0 ]]; then
+								_commands+=("$_command --max=99999999999999999999999999999999999999999999999999999999999")
+							fi
 						fi
 					fi
 				else
 					missing_files_str=$(join_by "," $missing_files)
-					yellow_text "Not all required files are there to test the $possible_plot_type function, missing files: $missing_files_str"
+					#yellow_text "Not all required files are there to test the $possible_plot_type function, missing files: $missing_files_str"
 				fi
 			else
 				yellow_text "Plot-type: $possible_plot_type: --save_to_file is not possible"
@@ -240,110 +262,123 @@ for projectname in "${test_projects[@]}"; do
 	fi
 done
 
+export DONT_INSTALL_MODULES=1
 i=0
 for _command in "${_commands[@]}"; do
-	this_img=$(echo $_command | sed -e 's#.*--save_to_file=##' -e 's#\s.*##')
-	possible_plot_type=$(echo $_command | sed -e 's#.*--plot_type=##' -e 's#\s.*##')
-	projectname=$(echo $_command | sed -e 's#.*--run_dir=##' -e 's#\s.*##' -e 's#.*/\(.*\)/[0-9]*$#\1#')
-	has_min=$(echo $_command | grep -- "--min" | wc -l)
-	has_max=$(echo $_command | grep -- "--max" | wc -l)
-
-	msg=""
-
-	if [[ $has_min -gt 0 ]]; then
-		msg="--min"
-	fi
-
-	if [[ $has_max -gt 0 ]]; then
-		msg="$msg, --max"
-	fi
-
-	msg=$(echo "$msg" | sed -e 's#^, ##' -e 's#^#(#' -e 's#$#)#' -e 's#()##')
-	if [[ -n $msg ]]; then
-		msg=" $msg"
-	fi
-
-	PROGRESSBAR=$(generate_progress_bar $i ${#_commands[@]})
-	green_reset_line "$PROGRESSBAR Plot-Tests $possible_plot_type/$this_img$msg"
-
-	if [[ -n $SHOW_COMMAND_BEFORE_EXECUTION ]]; then
-		echo ""
-		echo "$_command"
-	fi
-
-	START_TIME=$SECONDS
-	$_command
-	_exit_code=$?
-
-	END_TIME=$SECONDS
-	RUN_TIME=$(($END_TIME-$START_TIME))
-
-	if [[ "$projectname" == "nonutf8" ]]; then
-		if [[ "$_exit_code" -ne 7 ]]; then
-			echo ""
-			red_text "$_command failed. Required exit-code: 7, got exit-code $_exit_code (took $RUN_TIME seconds)"
-			errors+=("$_command failed. Required exit-code: 7, got exit-code $_exit_code (took $RUN_TIME seconds)")
-		fi
-	elif [[ "$projectname" == "empty_resultsfile" ]]; then
-		if [[ "$_exit_code" -ne 19 ]]; then
-			echo ""
-			red_text "$_command failed. Required exit-code: 19, got exit-code $_exit_code (took $RUN_TIME seconds)"
-			errors+=("$_command failed. Required exit-code: 19, got exit-code $_exit_code (took $RUN_TIME seconds)")
-		fi
+	if [[ $exit_on_first_error -eq 1 ]] && [[ ${#errors[@]} -gt 0 ]]; then
+		echo "Skipping command $_command because an error has occured earlier and --exit_on_first_error is set"
 	else
-		if [[ "$projectname" == "no_result" ]] || [[ "$projectname" == "defective_files" ]] || [[ "$projectname" == "empty_resultsfile" ]] ; then
-			true # Do nothing here. Do not count jobs in these folders as fails
-		else
-			if [[ "$_exit_code" -ne 0 ]]; then
-				echo ""
-				red_text "$_command failed (took $RUN_TIME seconds)"
-				errors+=("$_command failed (took $RUN_TIME seconds)")
-			fi
+		this_img="$(echo $_command | sed -e 's#.*--save_to_file=##' -e 's#\s.*##')"
+		possible_plot_type=$(echo $_command | sed -e 's#.*--plot_type=##' -e 's#\s.*##')
+		projectname=$(echo $_command | sed -e 's#.*--run_dir=##' -e 's#\s.*##' -e 's#.*/\(.*\)/[0-9]*$#\1#')
+		has_min=$(echo $_command | grep -- "--min" | wc -l)
+		has_max=$(echo $_command | grep -- "--max" | wc -l)
+
+		msg=""
+
+		if [[ $has_min -gt 0 ]]; then
+			msg="--min"
 		fi
 
-		if [[ -e "$this_img" ]]; then
-			if [[ $(cat "$this_img" | grep svg | wc -l 2>/dev/null) -lt 2 ]]; then
+		if [[ $has_max -gt 0 ]]; then
+			msg="$msg, --max"
+		fi
+
+		msg=$(echo "$msg" | sed -e 's#^, ##' -e 's#^#(#' -e 's#$#)#' -e 's#()##')
+		if [[ -n $msg ]]; then
+			msg=" $msg"
+		fi
+
+		nr_cmds=${#_commands[@]}
+
+		PROGRESSBAR=$(generate_progress_bar $(($i+1)) $nr_cmds)
+		green_reset_line "$PROGRESSBAR $i/${#_commands[@]} Plot-Tests $possible_plot_type/$this_img$msg"
+
+		if [[ -n $SHOW_COMMAND_BEFORE_EXECUTION ]]; then
+			echo ""
+			echo "$_command"
+		fi
+
+		START_TIME=$SECONDS
+		eval "$_command"
+		_exit_code=$?
+
+		END_TIME=$SECONDS
+		RUN_TIME=$(($END_TIME-$START_TIME))
+
+		if [[ "$projectname" == "nonutf8" ]]; then
+			if [[ "$_exit_code" -ne 7 ]]; then
 				echo ""
-				red_text "$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code (took $RUN_TIME seconds)"
-				errors+=("$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code (took $RUN_TIME seconds)")
-			else
-				MISSING_OUTPUTS=()
-
-				saved_IFS=$IFS
-				IFS=$'\n'
-				for needed_output in $(cat .omniopt_plot_${possible_plot_type}.py | grep "TEST_OUTPUT_MUST_CONTAIN" | sed -e 's#.*TEST_OUTPUT_MUST_CONTAIN:\s##g'); do
-					if ! grep "$needed_output" "$this_img" 2>/dev/null >/dev/null; then
-						MISSING_OUTPUTS+=("$needed_output")
-					fi
-				done
-
-				if [ ${#MISSING_OUTPUTS[@]} -eq 0 ]; then
-					green_reset_line "$PROGRESSBAR OK Plot-Tests $possible_plot_type/$this_img"
-					if [[ "$keep_tmp" -eq 0 ]]; then
-						rm -f "$this_img" || {
-							echo ""
-							red_text "Could not remove $this_img. ls -aslrt1 (took $RUN_TIME seconds):"
-							ls -aslrt1 "$this_img"
-							exit 5
-						}
-					fi
-				else
-					if [[ "$possible_plot_type" == "no_result" ]]; then
-						missing_outputs_str=$(join_by ", " $MISSING_OUTPUTS)
-						echo ""
-						red_text "$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code (took $RUN_TIME seconds)"
-						errors+=("$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code (took $RUN_TIME seconds)")
-					fi
-				fi
-				IFS=$saved_IFS
+				red_text "$_command failed. Required exit-code: 7, got exit-code $_exit_code (took $RUN_TIME seconds)"
+				errors+=("$_command failed. Required exit-code: 7, got exit-code $_exit_code (took $RUN_TIME seconds)")
+			fi
+		elif [[ "$projectname" == "empty_resultsfile" ]]; then
+			if [[ "$_exit_code" -ne 19 ]]; then
+				echo ""
+				red_text "$_command failed. Required exit-code: 19, got exit-code $_exit_code (took $RUN_TIME seconds)"
+				errors+=("$_command failed. Required exit-code: 19, got exit-code $_exit_code (took $RUN_TIME seconds)")
 			fi
 		else
 			if [[ "$projectname" == "no_result" ]] || [[ "$projectname" == "defective_files" ]] || [[ "$projectname" == "empty_resultsfile" ]] ; then
-				green_reset_line "$PROGRESSBAR OK Plot-Tests $possible_plot_type/$this_img"
+				true # Do nothing here. Do not count jobs in these folders as fails
 			else
-				echo ""
-				red_text "$_command: $this_img does not exist (took $RUN_TIME seconds)"
-				errors+=("$_command: $this_img does not exist (took $RUN_TIME seconds)")
+				if [[ "$_exit_code" -ne 0 ]]; then
+					echo ""
+					red_text "$_command failed (took $RUN_TIME seconds)"
+					errors+=("$_command failed (took $RUN_TIME seconds)")
+				fi
+			fi
+
+			if [[ -e "$this_img" ]]; then
+				if [[ $(cat "$this_img" | grep svg | wc -l 2>/dev/null) -lt 2 ]]; then
+					echo ""
+					red_text "$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code (took $RUN_TIME seconds)"
+					errors+=("$_command: $this_img does not have enough <svg> tags, exit_code: $_exit_code (took $RUN_TIME seconds)")
+				else
+					MISSING_OUTPUTS=()
+
+					saved_IFS=$IFS
+					IFS=$'\n'
+					for needed_output in $(cat .omniopt_plot_${possible_plot_type}.py | grep "TEST_OUTPUT_MUST_CONTAIN" | sed -e 's#.*TEST_OUTPUT_MUST_CONTAIN:\s##g'); do
+						if ! grep "$needed_output" "$this_img" 2>/dev/null >/dev/null; then
+							MISSING_OUTPUTS+=("$needed_output")
+						fi
+					done
+
+					if [[ $projectname -eq "maximize_test" ]]; then
+						if ! grep "Maximum of" "$this_img" 2>/dev/null >/dev/null; then
+							MISSING_OUTPUTS+=("Maximum of")
+						fi					
+					fi
+
+					if [ ${#MISSING_OUTPUTS[@]} -eq 0 ]; then
+						green_reset_line "$PROGRESSBAR $i/${#_commands[@]} OK Plot-Tests $possible_plot_type/$this_img"
+						if [[ "$keep_tmp" -eq 0 ]]; then
+							rm -f "$this_img" || {
+								echo ""
+								red_text "Could not remove $this_img. ls -aslrt1 (took $RUN_TIME seconds):"
+								ls -aslrt1 "$this_img"
+								exit 5
+							}
+						fi
+					else
+						if [[ "$possible_plot_type" == "no_result" ]]; then
+							missing_outputs_str=$(join_by ", " $MISSING_OUTPUTS)
+							echo ""
+							red_text "$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code (took $RUN_TIME seconds)"
+							errors+=("$_command: Missing outputs: $missing_outputs_str, exit_code: $_exit_code (took $RUN_TIME seconds)")
+						fi
+					fi
+					IFS=$saved_IFS
+				fi
+			else
+				if [[ "$projectname" == "no_result" ]] || [[ "$projectname" == "defective_files" ]] || [[ "$projectname" == "empty_resultsfile" ]] ; then
+					green_reset_line "$PROGRESSBAR $i/${#_commands[@]} OK Plot-Tests $possible_plot_type/$this_img"
+				else
+					echo ""
+					red_text "$_command: $this_img does not exist (took $RUN_TIME seconds)"
+					errors+=("$_command: $this_img does not exist (took $RUN_TIME seconds)")
+				fi
 			fi
 		fi
 	fi
@@ -351,15 +386,14 @@ for _command in "${_commands[@]}"; do
 done
 PROGRESSBAR=$(generate_progress_bar $i ${#_commands[@]})
 
-green_reset_line "$PROGRESSBAR $i tests ran, ${#errors[@]} failed"
-
+green_reset_line "$PROGRESSBAR $i tests ran, ${#errors[@]} failed\n"
 
 secs=$SECONDS
 hrs=$(( secs/3600 )); mins=$(( (secs-hrs*3600)/60 )); secs=$(( secs-hrs*3600-mins*60 ))
 printf "\nPlot test took: %02d:%02d:%02d\n" $hrs $mins $secs
 
 if [ ${#errors[@]} -eq 0 ]; then
-	green_text "No plot errors"
+	green_text "No plot errors\n"
 else
 	echo ""
 	red_text "=> PLOT-ERRORS => PLOT-ERRORS => PLOT-ERRORS =>"
@@ -372,5 +406,29 @@ else
 fi
 
 echo ""
+
+if [[ -z $OO_MAIN_TESTS ]]; then
+	if [[ -n $RUN_WITH_COVERAGE ]]; then
+		if command -v coverage 2>/dev/null >/dev/null; then
+			coverage combine 2>/dev/null >/dev/null
+			coverage xml 2>/dev/null >/dev/null
+			coverage json 2>/dev/null >/dev/null
+			coverage report
+
+			if [[ -n $GITHUB_STEP_SUMMARY ]]; then
+				echo "$(coverage report --format=markdown)" >> "$GITHUB_STEP_SUMMARY"
+			fi
+
+			if [[ -z $CI ]] && [[ -n $DISPLAY ]] && command -v firefox 2>/dev/null >/dev/null; then
+				coverage html 2>/dev/null >/dev/null
+				firefox htmlcov/index.html
+			fi
+		else
+			red_text "--run_with_coverage was defined, but coverage could not be found"
+		fi
+	fi
+fi
+
+
 exit ${#errors[@]}
 }
diff --git a/ax/.tests/start_simple_optimization_run b/ax/.tests/start_simple_optimization_run
--- a/ax/.tests/start_simple_optimization_run
+++ b/ax/.tests/start_simple_optimization_run
@@ -1,8 +1,24 @@
 #!/bin/bash
 
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+CYAN='\033[0;36m'
+MAGENTA='\033[0;35m'
+NC='\033[0m'
+
+function set_debug {
+	trap 'echo -e "${CYAN}$(date +"%Y-%m-%d %H:%M:%S")${NC} ${MAGENTA}| Line: $LINENO ${NC}${YELLOW}-> ${NC}${BLUE}[DEBUG]${NC} ${GREEN}$BASH_COMMAND${NC}"' DEBUG
+}
+
+function unset_debug {
+	trap - DEBUG
+}
+
 export OO_MAIN_TESTS=1
 
 int_re='^[+-]?[0-9]+$'
+
 function echoerr() {
 	echo "$@" 1>&2
 }
@@ -19,35 +35,40 @@ function green_text {
 	echoerr -e "\e\033[0;32m$1\e[0m"
 }
 
-
 function calltracer () {
 	if [[ $EXPECTED_TO_FAIL -ne "1" ]]; then
 		yellow_text "Git status hash:"
 		git rev-parse HEAD
-		red_text 'Error occured in file/line:'
+		red_text 'Error occurred in file/line:'
 		caller
 	fi
 }
 
 trap 'calltracer' ERR
 
+# Help Function
 function help () {
 	echo "Possible options:"
-	echo "  --max_eval=(INT)                                   Number of max evals for this test"
-	echo "  --num_parallel_jobs (INT)                          Number of max parallel workers for this test"
-	echo "  --num_random_steps=(INT)                           Number of random steps"
-	echo "  --model=STR                                        Model name"
-	echo "  --gridsearch                                       Do gridsearch"
-	echo "  --gpus=(INT)                                       Nr of GPUs per worker"
-	echo "  --time=(INT)                                       Time each subjob should run"
-	echo "  --allow_failure                                    Adds a param to randomly fail"
-	echo "  --help                                             this help"
-	echo "  --debug                                            Enables debug mode (set -x)"
+	echo "  --max_eval=(INT)          Maximum number of evaluations for this test"
+	echo "  --mem_gb=(INT)            Memory in GB (0 for all)"
+	echo "  --num_parallel_jobs=(INT) Maximum number of parallel workers for this test"
+	echo "  --num_random_steps=(INT)  Number of random steps"
+	echo "  --model=STR               Model name"
+	echo "  --gridsearch              Perform grid search"
+	echo "  --gpus=(INT)              Number of GPUs per worker"
+	echo "  --time=(INT)              Time each subjob should run"
+	echo "  --allow_failure           Adds a parameter to randomly fail"
+	echo "  --force_local_execution   Run locally even if SLURM is installed"
+	echo "  --all_float               Use all_float logic"
+	echo "  --one_param               One parameter"
+	echo "  --two_params              Two parameters"
+	echo "  --help                    This help"
+	echo "  --debug                   Enable debug mode"
 	exit $1
 }
 
 NUM_GPUS=0
-if command -v nvidia-smi 2>/dev/null >/dev/null; then
+if command -v nvidia-smi >/dev/null 2>&1; then
 	NUM_GPUS=$(nvidia-smi --list-gpus | wc -l)
 fi
 
@@ -60,9 +81,113 @@ debug=0
 max_eval=30
 num_parallel_jobs=20
 allow_failure=0
+force_local_execution=0
 num_random_steps=$num_parallel_jobs
 time=60
 model=BOTORCH_MODULAR
+mem_gb=4
+all_float=0
+one_param=0
+
+function parse_argument() {
+	local arg="$1"
+	local var_name="$2"
+	local is_int="$3"
+
+	if [[ "$arg" == *=* ]]; then
+		value="${arg#*=}"
+	else
+		value="$2"
+		shift
+	fi
+
+	if [[ -n $value ]]; then
+		if [[ "$is_int" -eq 1 ]]; then
+			if ! [[ "$value" =~ $int_re ]]; then
+				red_text "Error: --${var_name} must be an integer: $arg" >&2
+				exit 100
+			fi
+		fi
+	fi
+
+	eval "$var_name=\"$value\""
+}
+
+function build_omniopt_command_all_float() {
+	local cmd=("./omniopt" "--partition=$PARTITION" "--experiment_name=example_all_float" "--mem_gb=$mem_gb" "--time=$time" "--worker_timeout=5" "--max_eval=$max_eval" "--num_parallel_jobs=$num_parallel_jobs" "--gpus=$NUM_GPUS" "--num_random_steps=$num_random_steps" "--follow" "--send_anonymized_usage_stats" "--run_program=$(echo ".tests/optimization_example_all_float --x=%(x) --y=%(y) --z=%(z) --a=%(a)" | base64 -w 0)" "--cpus_per_task=1" "--nodes_per_job=1" "--model=BOTORCH_MODULAR" "--run_mode=local" "--parameter" "x range -1000 1000 float" "--parameter" "y range -1000 1000 float" "--parameter" "z range -1000 1000 float" "--parameter" "a range -1000 1000 float" "--live_share")
+
+	if [[ "$gridsearch" -eq "1" ]]; then
+		cmd+=("--gridsearch")
+	fi
+
+	if [[ "$allow_failure" -eq "1" ]]; then
+		cmd+=("--parameter" "fail_or_not choice \"0,1\"")
+		cmd=("${cmd[@]/--run_program=$(echo ".tests/optimization_example_all_float --x=%(x) --y=%(y) --z=%(z) --a=%(a)" | base64 -w 0)/$(echo ".tests/optimization_example_all_float --x=%(x) --y=%(y) --z=%(z) --a=%(a) --fail_or_not=%(fail_or_not)" | base64 -w 0)}")
+	fi
+
+	if [[ "$force_local_execution" -eq "1" ]]; then
+		cmd+=("--force_local_execution")
+	fi
+
+	echo "${cmd[@]}"
+}
+
+function build_omniopt_command_standard() {
+	local base_cmd=("./omniopt" "--live_share" "--send_anonymized_usage_stats" "--partition" "$PARTITION" "--experiment_name" "$TESTNAME" "--mem_gb=$mem_gb" "--time" "$time" "--worker_timeout=5" "--max_eval" "$max_eval" "--num_parallel_jobs" "$num_parallel_jobs" "--gpus" "$NUM_GPUS" "--run_program" "$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0)" "--parameter" "int_param range -100 10 int" "--parameter" "float_param range -100 10 float" "--parameter" "choice_param choice 1,2,4,8,16,hallo" "--parameter" "int_param_two range -100 10 int" "--follow" "--num_random_steps" "$num_random_steps" "--model" "$model" "--auto_exclude_defective_hosts" "--hide_ascii_plots")
+
+	if [[ "$gridsearch" -eq "1" ]]; then
+		base_cmd+=("--gridsearch")
+	fi
+
+	if [[ "$allow_failure" -eq "1" ]]; then
+		base_cmd+=("--parameter" "fail_or_not choice \"0,1\"")
+		base_cmd=("${base_cmd[@]/--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0)/$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0)}")
+	fi
+
+	if [[ "$force_local_execution" -eq "1" ]]; then
+		base_cmd+=("--force_local_execution")
+	fi
+
+	echo "${base_cmd[@]}"
+}
+
+function build_omniopt_command_one_param() {
+	local cmd=("./omniopt" "--live_share" "--send_anonymized_usage_stats" "--partition" "$PARTITION" "--experiment_name" "$TESTNAME" "--mem_gb=$mem_gb" "--time" "$time" "--worker_timeout=5" "--max_eval" "$max_eval" "--num_parallel_jobs" "$num_parallel_jobs" "--gpus" "$NUM_GPUS" "--run_program" "$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='1' --choice_param='1'  --int_param_two='1'" | base64 -w 0)" "--parameter" "int_param range -100 10 int" "--follow" "--num_random_steps" "$num_random_steps" "--model" "$model" "--hide_ascii_plots")
+
+	if [[ "$gridsearch" -eq "1" ]]; then
+		cmd+=("--gridsearch")
+	fi
+
+	if [[ "$allow_failure" -eq "1" ]]; then
+		cmd+=("--parameter" "fail_or_not choice \"0,1\"")
+		cmd=("${cmd[@]/--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='1' --choice_param='1'  --int_param_two='1'" | base64 -w 0)/$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='1' --choice_param='1'  --int_param_two='1' --fail_or_not=%(fail_or_not)" | base64 -w 0)}")
+	fi
+
+	if [[ "$force_local_execution" -eq "1" ]]; then
+		cmd+=("--force_local_execution")
+	fi
+
+	echo "${cmd[@]}"
+}
+
+function build_omniopt_command_two_params() {
+	local cmd=("./omniopt" "--live_share" "--send_anonymized_usage_stats" "--partition" "$PARTITION" "--experiment_name" "$TESTNAME" "--mem_gb=$mem_gb" "--time" "$time" "--worker_timeout=5" "--max_eval" "$max_eval" "--num_parallel_jobs" "$num_parallel_jobs" "--gpus" "$NUM_GPUS" "--run_program" "$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='1' --choice_param='1'  --int_param_two='1'" | base64 -w 0)" "--parameter" "int_param range -100 10 int" "--parameter" "float_param range -100 10 float" "--follow" "--num_random_steps" "$num_random_steps" "--model" "$model" "--hide_ascii_plots")
+
+	if [[ "$gridsearch" -eq "1" ]]; then
+		cmd+=("--gridsearch")
+	fi
+
+	if [[ "$allow_failure" -eq "1" ]]; then
+		cmd+=("--parameter" "fail_or_not choice \"0,1\"")
+		cmd=("${cmd[@]/--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='1' --choice_param='1'  --int_param_two='1'" | base64 -w 0)/$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='1'  --int_param_two='1'"| base64 -w 0)}")
+	fi
+
+	if [[ "$force_local_execution" -eq "1" ]]; then
+		cmd+=("--force_local_execution")
+	fi
+
+	echo "${cmd[@]}"
+}
 
 args=("$@")
 k=0
@@ -70,247 +195,127 @@ while [ $k -lt ${#args[@]} ]; do
 	i="${args[k]}"
 
 	case $i in
+		--all_float=*|--all_float)
+			all_float=1
+			;;
+		--force_local_execution)
+			force_local_execution=1
+			;;
 		--allow_failure)
 			allow_failure=1
 			;;
 		--gridsearch)
 			gridsearch=1
-			shift
 			;;
-
-		--time=*)
-			time="${i#*=}"
-			if ! [[ $time =~ $int_re ]] ; then
-				red_text "error: --time not a INT: $i" >&2
-				exit 100
-			fi
+		--one_param)
+			one_param=1
 			;;
-		--time)
-			shift
-			k=$((k+1))
-
-			time="${args[k]}"
-			if ! [[ $time =~ $int_re ]] ; then
-				red_text "error: --time not a INT: $i" >&2
-				exit 100
-			fi
+		--two_params)
+			two_params=1
 			;;
-		--max_eval=*)
-			max_eval="${i#*=}"
-			if ! [[ $max_eval =~ $int_re ]] ; then
-				red_text "error: --max_eval not a INT: $i" >&2
-				exit 100
-			fi
+		--mem_gb=*|--mem_gb)
+			parse_argument "$i" "mem_gb" 1
 			;;
-		--max_eval)
-			shift
-			k=$((k+1))
-
-			max_eval="${args[k]}"
-			if ! [[ $max_eval =~ $int_re ]] ; then
-				red_text "error: --max_eval not a INT: $i" >&2
-				exit 100
-			fi
-
+		--time=*|--time)
+			parse_argument "$i" "time" 1
 			;;
-
-		--model=*)
-			model="${i#*=}"
+		--max_eval=*|--max_eval)
+			parse_argument "$i" "max_eval" 1
 			;;
-		--model)
-			shift
-			k=$((k+1))
-
-			model="${args[k]}"
+		--model=*|--model)
+			parse_argument "$i" "model" 0
 			;;
-
-		--num_random_steps=*)
-			num_random_steps="${i#*=}"
-			if ! [[ $num_random_steps =~ $int_re ]] ; then
-				red_text "error: --num_random_steps not a INT: $i" >&2
-				exit 100
-			fi
-
+		--num_random_steps=*|--num_random_steps)
+			parse_argument "$i" "num_random_steps" 1
 			;;
-		--num_random_steps)
-			shift
-			k=$((k+1))
-
-			num_random_steps="${args[k]}"
-			if ! [[ $num_random_steps =~ $int_re ]] ; then
-				red_text "error: --num_random_steps not a INT: $i" >&2
-				exit 100
-			fi
-
+		--num_parallel_jobs=*|--num_parallel_jobs)
+			parse_argument "$i" "num_parallel_jobs" 1
 			;;
-		--num_parallel_jobs=*)
-			num_parallel_jobs="${i#*=}"
-			if ! [[ $num_parallel_jobs =~ $int_re ]] ; then
-				red_text "error: --num_parallel_jobs not a INT: $i" >&2
-				exit 100
-			fi
-
+		--gpus=*|--gpus)
+			parse_argument "$i" "NUM_GPUS" 1
 			;;
-		--num_parallel_jobs)
-			shift
-			k=$((k+1))
-
-			num_parallel_jobs="${args[k]}"
-			if ! [[ $num_parallel_jobs =~ $int_re ]] ; then
-				red_text "error: --num_parallel_jobs not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--gpus=*)
-			NUM_GPUS="${i#*=}"
-			if ! [[ $NUM_GPUS =~ $int_re ]] ; then
-				red_text "error: --gpus not a INT: $i" >&2
-				exit 100
-			fi
-
-			;;
-		--gpus)
-			shift
-			k=$((k+1))
-
-			NUM_GPUS="${args[k]}"
-			if ! [[ $NUM_GPUS =~ $int_re ]] ; then
-				red_text "error: --gpus not a INT: $i" >&2
-				exit 100
-			fi
-			;;
-
 		--help*)
-			help 1
+			help 0
 			;;
 		--debug)
 			debug=1
 			;;
-
 		*)
-			red_text "Unknown parameter $i"
+			red_text "Unknown parameter: $i"
 			exit 2
 			;;
 	esac
 	k=$((k+1))
 done
 
+if [[ $one_param -eq 1 ]] && [[ $two_params -eq 1 ]]; then
+	red_text "--one_param and --two_params cannot be combined."
+	exit 1
+fi
+
+if [[ $one_param -eq 1 ]] && [[ $all_float -eq 1 ]]; then
+	red_text "--one_param cannot be used with --all_float."
+	exit 1
+fi
+
+if [[ $two_params -eq 1 ]] && [[ $all_float -eq 1 ]]; then
+	red_text "--two_params cannot be used with --all_float."
+	exit 1
+fi
+
 if [[ "$num_parallel_jobs" -lt "1" ]]; then
-	red_text "num_parallel_jobs must be 1 or more, is $num_parallel_jobs"
+	red_text "num_parallel_jobs must be larger than 1, is $num_parallel_jobs"
 	exit 1
 fi
 
 if [[ "$max_eval" -lt "1" ]]; then
-	red_text "Max_eval must be 1 or more, is $max_eval"
+	red_text "max_eval must be larger than 1, is $max_eval"
 	exit 1
 fi
 
 if [[ "$debug" -eq "1" ]]; then
-	set -x
+	set_debug
 fi
 
-
 PARTITION="alpha"
-TESTNAME=__main__tests__
+TESTNAME="__main__tests__${model}__"
+
+if [[ "$force_local_execution" -eq "1" ]]; then
+	TESTNAME="${TESTNAME}_local"
+fi
 
 if [[ "$gridsearch" -eq "1" ]]; then
 	TESTNAME="${TESTNAME}_gridsearch"
-	if [[ "$allow_failure" -eq "0" ]]; then
-		./omniopt \
-			--send_anonymized_usage_stats \
-			--partition $PARTITION \
-			--experiment_name $TESTNAME \
-			--mem_gb=5 \
-			--time $time \
-			--worker_timeout=5 \
-			--max_eval $max_eval \
-			--num_parallel_jobs $num_parallel_jobs \
-			--gpus $NUM_GPUS \
-			--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-			--parameter int_param range -100 10 int \
-			--parameter float_param range -100 10 float \
-			--parameter choice_param choice 1,2,4,8,16,hallo \
-			--parameter int_param_two range -100 10 int \
-			--follow \
-			--num_random_steps $num_random_steps \
-			--model $model \
-			--auto_exclude_defective_hosts \
-			--gridsearch \
-			--hide_ascii_plots
-		exit_code=$?
-	else
-		./omniopt \
-			--send_anonymized_usage_stats \
-			--partition $PARTITION \
-			--experiment_name $TESTNAME \
-			--mem_gb=5 \
-			--time $time \
-			--worker_timeout=5 \
-			--max_eval $max_eval \
-			--num_parallel_jobs $num_parallel_jobs \
-			--gpus $NUM_GPUS \
-			--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0) \
-			--parameter int_param range -100 10 int \
-			--parameter float_param range -100 10 float \
-			--parameter choice_param choice 1,2,4,8,16,hallo \
-			--parameter int_param_two range -100 10 int \
-			--parameter fail_or_not choice "0,1" \
-			--follow \
-			--num_random_steps $num_random_steps \
-			--model $model \
-			--auto_exclude_defective_hosts \
-			--gridsearch \
-			--hide_ascii_plots
-		exit_code=$?
-	fi
 else
-	if [[ "$allow_failure" -eq "0" ]]; then
-		./omniopt \
-			--send_anonymized_usage_stats \
-			--partition $PARTITION \
-			--experiment_name $TESTNAME \
-			--mem_gb=5 \
-			--time $time \
-			--worker_timeout=5 \
-			--max_eval $max_eval \
-			--num_parallel_jobs $num_parallel_jobs \
-			--gpus $NUM_GPUS \
-			--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
-			--parameter int_param range -100 10 int \
-			--parameter float_param range -100 10 float \
-			--parameter choice_param choice 1,2,4,8,16,hallo \
-			--parameter int_param_two range -100 10 int \
-			--follow \
-			--num_random_steps $num_random_steps \
-			--model $model \
-			--auto_exclude_defective_hosts \
-			--hide_ascii_plots
-		exit_code=$?
+	TESTNAME="${TESTNAME}_nogridsearch"
+fi
+
+if [[ "$one_param" -eq "1" ]]; then
+	TESTNAME="__main__tests__${model}__one_param"
+
+	if [[ "$force_local_execution" -eq "1" ]]; then
+		TESTNAME="${TESTNAME}_local"
+	fi
+
+	if [[ "$gridsearch" -eq "1" ]]; then
+		TESTNAME="${TESTNAME}_gridsearch"
 	else
-		./omniopt \
-			--send_anonymized_usage_stats \
-			--partition $PARTITION \
-			--experiment_name $TESTNAME \
-			--mem_gb=5 \
-			--time $time \
-			--worker_timeout=5 \
-			--max_eval $max_eval \
-			--num_parallel_jobs $num_parallel_jobs \
-			--gpus $NUM_GPUS \
-			--run_program $(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0) \
-			--parameter int_param range -100 10 int \
-			--parameter float_param range -100 10 float \
-			--parameter choice_param choice 1,2,4,8,16,hallo \
-			--parameter int_param_two range -100 10 int \
-			--parameter fail_or_not choice "0,1" \
-			--follow \
-			--num_random_steps $num_random_steps \
-			--model $model \
-			--auto_exclude_defective_hosts \
-			--hide_ascii_plots
-		exit_code=$?
+		TESTNAME="${TESTNAME}_nogridsearch"
 	fi
 fi
+
+if [[ "$one_param" -eq "1" ]]; then
+	omniopt_cmd=$(build_omniopt_command_one_param)
+elif [[ "$all_float" -eq "1" ]]; then
+	omniopt_cmd=$(build_omniopt_command_all_float)
+elif [[ "$two_params" -eq "1" ]]; then
+	omniopt_cmd=$(build_omniopt_command_two_params)
+else
+	omniopt_cmd=$(build_omniopt_command_standard)
+fi
+
+green_text "$omniopt_cmd"
+eval "$omniopt_cmd"
+exit_code=$?
 
 exit $exit_code
diff --git a/ax/omniopt_docker b/ax/omniopt_docker
--- a/ax/omniopt_docker
+++ b/ax/omniopt_docker
@@ -11,7 +11,7 @@ cd "$SCRIPT_DIR"
 help_message() {
 	echo "Usage: docker [OPTIONS]"
 	echo "Options:"
-	echo "  --help             Show this help message"
+	echo "  --help             This help"
 }
 
 function _mkdir {
@@ -56,34 +56,23 @@ function apt_get_update () {
 
 # Check if Docker is installed
 if ! command -v docker &>/dev/null; then
-	if command -v apt >/dev/null; then
-		if [[ ! -e /etc/apt/sources.list ]]; then
-			echo "/etc/apt/sources.list not found. Cannot continue. You must install docker manually."
-			exit 1
-		fi
-		echo "Docker not found. Installing Docker..."
-		if [[ -e /etc/apt/sources.list ]]; then
-			echo "Enabling non-free repository..."
-			sudo sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list || {
-				echo "Could not edit /etc/apt/sources.list. Exiting."
-				exit 10
-			}
-			echo "Enabled! non-free repository."
-		fi
+	curl -fsSL "https://get.docker.com" | bash
 
-		UPDATED_PACKAGES=0
-		apt_get_update
+	exit_code=$?
 
-
-		# Install Docker
-		sudo apt install -y docker.io || {
-			echo "sudo apt install -y docker.io failed. Try adding the repository for docker manually."
-			exit 3
-		}
-	else
-		echo "Can only auto-install docker on debian systems. You need to install docker yourself on your distro."
-		exit 11
+	if [[ $exit_code -ne 0 ]]; then
+		echo "Failed to install docker"
+		exit 2
 	fi
+fi
+
+if ! command -v docker-compose &>/dev/null; then
+	apt_get_update
+
+	sudo apt-get install -y docker-compose|| {
+		echo "sudo apt install -y docker-compose failed"
+		exit 3
+	}
 fi
 
 if ! command -v wget &>/dev/null; then
@@ -95,13 +84,14 @@ if ! command -v wget &>/dev/null; then
 	}
 fi
 
-if ! command -v xhost &>/dev/null; then
-	apt_get_update
-
-	sudo apt-get install -y xhost || {
-		echo "sudo apt install -y xhost failed"
-		exit 4
-	}
+if [[ -n $DISPLAY ]]; then
+	if ! command -v xhost &>/dev/null; then
+		apt_get_update
+		sudo apt-get install -y xhost || {
+			echo "sudo apt install -y xhost failed"
+			exit 4
+		}
+	fi
 fi
 
 
@@ -126,7 +116,7 @@ echo "=== Current git hash before auto-pulling ==="
 git pull
 
 _mkdir runs
-_mkdir .logs
+_mkdir logs
 
 git rev-parse HEAD > git_hash
 
@@ -162,10 +152,10 @@ fi
 _mkdir $HOME/.config/matplotlib_docker_omniopt
 
 case "$ORIGINAL_ARGS" in
-	omniopt*|./.tests/*)
+	./omniopt*|omniopt*|./.tests/*|.tests/*)
 		if [[ -z $DISPLAY ]]; then
 			docker run \
-				-v $(pwd)/.logs:/var/opt/omniopt/.logs:rw \
+				-v $(pwd)/logs:/var/opt/omniopt/logs:rw \
 				-v $(pwd)/runs:/var/opt/omniopt/runs:rw \
 				-v $(pwd)/:/var/opt/omniopt/docker_user_dir:rw \
 				-v /$HOME/.config/matplotlib_docker_omniopt:$HOME/.config/matplotlib:rw \
@@ -174,7 +164,7 @@ case "$ORIGINAL_ARGS" in
 				ax_omniopt2 bash /var/opt/omniopt/$ORIGINAL_ARGS
 		else
 			docker run \
-				-v $(pwd)/.logs:/var/opt/omniopt/.logs:rw \
+				-v $(pwd)/logs:/var/opt/omniopt/logs:rw \
 				-v $(pwd)/runs:/var/opt/omniopt/runs:rw \
 				-v $(pwd)/:/var/opt/omniopt/docker_user_dir:rw \
 				-v $HOME/.config/matplotlib_docker_omniopt:/$HOME/.config/matplotlib:rw \
@@ -191,7 +181,7 @@ case "$ORIGINAL_ARGS" in
 		fi
 		;;
 	*)
-		echo "Error: The argument does not start with one of the valid prefixes, i.e. 'omniopt*' or './.tests/*'. Argument was: $ORIGINAL_ARGS"
+		echo "Error: The argument does not start with one of the valid prefixes, i.e. 'omniopt*', '.tests/' or './.tests/*'. Argument was: $ORIGINAL_ARGS"
 		exit 1
 		;;
 esac
