fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,12 +18,12 @@ jobs:
       contents: write
 
     steps:
-      - name: Cache Python packages
-        uses: actions/cache@v4
-        with:
-          path: |
-            $HOME/.cache/pip
-            $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
+    - name: Cache Python packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          $HOME/.cache/pip
+          $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
         key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
@@ -34,18 +34,18 @@ jobs:
     - name: Install dependencies
       run: |
         if [[ $RUNNER_OS == 'Linux' ]]; then
-        if grep -q '^ID=ubuntu' /etc/os-release; then
-        sudo apt-get update || sudo apt-get update || sudo apt-get update
-        sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
-        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
-        sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          if grep -q '^ID=ubuntu' /etc/os-release; then
+            sudo apt-get update || sudo apt-get update || sudo apt-get update
+            sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
+            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
+            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          else
+            echo "Invalid OS for pipeline. Only works with Ubuntu"
+            exit 1
+          fi
         else
-        echo "Invalid OS for pipeline. Only works with Ubuntu"
-        exit 1
-        fi
-        else
-        echo "Invalid OS detected"
-        exit 2
+            echo "Invalid OS detected"
+            exit 2
         fi
     - name: Creating virtualenv
       run: |
@@ -53,7 +53,7 @@ jobs:
         source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
 
         if command -v brew; then
-        pip install psycopg2-binary
+          pip install psycopg2-binary
         fi
     - name: Installing stuff...
       run: |
@@ -75,69 +75,12 @@ jobs:
         os: [ubuntu-24.04] #, ubuntu-22.04, ubuntu-20.04] #, macos-14]
 
     steps:
-      - name: Cache Python packages
-        uses: actions/cache@v4
-        with:
-          path: |
-            $HOME/.cache/pip
-            $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
-        key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
-
-    - name: Checkout code
-      uses: actions/checkout@v4
-
-    - name: Install dependencies
-      run: |
-        if [[ $RUNNER_OS == 'Linux' ]]; then
-        if grep -q '^ID=ubuntu' /etc/os-release; then
-        sudo apt-get update || sudo apt-get update || sudo apt-get update
-        sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
-        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
-        sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
-        else
-        echo "Invalid OS for pipeline. Only works with Ubuntu"
-        exit 1
-        fi
-        else
-        echo "Invalid OS detected"
-        exit 2
-        fi
-    - name: Creating virtualenv
-      run: |
-        python3 -mvenv $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')
-        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
-
-        if command -v brew; then
-        pip install psycopg2-binary
-        fi
-    - name: Installing stuff...
-      run: |
-        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
-        pip install --no-cache-dir --upgrade pip
-        pip install --no-cache-dir setuptools
-        pip install --no-cache-dir pip wheel
-        pip install --no-cache-dir multidict
-
-    - name: main test script
-      run: |
-        ./ax/omniopt_docker .tests/main --num_random_steps=1 --max_eval=2 --exit_on_first_error --superquick
-
-  main-test:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: true
-      matrix:
-        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14]
-
-    steps:
-      - name: Cache Python packages
-        uses: actions/cache@v4
-        with:
-          path: |
-            $HOME/.cache/pip
-            $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
+    - name: Cache Python packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          $HOME/.cache/pip
+          $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
         key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
@@ -158,7 +101,65 @@ jobs:
             exit 1
           fi
         else
-          brew install python
+            echo "Invalid OS detected"
+            exit 2
+        fi
+    - name: Creating virtualenv
+      run: |
+        python3 -mvenv $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')
+        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
+
+        if command -v brew; then
+          pip install psycopg2-binary
+        fi
+    - name: Installing stuff...
+      run: |
+        source $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/bin/activate
+        pip install --no-cache-dir --upgrade pip
+        pip install --no-cache-dir setuptools
+        pip install --no-cache-dir pip wheel
+        pip install --no-cache-dir multidict
+
+    - name: main test script
+      run: |
+        ./ax/omniopt_docker .tests/main --num_random_steps=1 --max_eval=2 --exit_on_first_error --superquick
+
+  main-test:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: true
+      matrix:
+        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04] #, macos-14]
+
+    steps:
+    - name: Cache Python packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          $HOME/.cache/pip
+          $HOME/.omniax_$(uname -m)_Python_$(python3 --version | sed -e 's#Python ##')/
+        key: ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pip-${{ hashFiles('ax/requirements.txt') }}
+
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Install dependencies
+      run: |
+        if [[ $RUNNER_OS == 'Linux' ]]; then
+          if grep -q '^ID=ubuntu' /etc/os-release; then
+            sudo apt-get update || sudo apt-get update || sudo apt-get update
+            sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring
+            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
+            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          else
+            echo "Invalid OS for pipeline. Only works with Ubuntu"
+            exit 1
+          fi
+        else
+            echo "Invalid OS detected"
+            exit 2
         fi
     - name: Creating virtualenv
       run: |
